### MFN

In [1]:
import pandas as pd

base = "kazakhstan/mfn/"   # change if needed

df1  = pd.read_csv(base + "MFN_KAZ_2013.CSV")
df2  = pd.read_csv(base + "MFN_KAZ_2014.CSV")
df3  = pd.read_csv(base + "MFN_KAZ_2015.CSV")
df4  = pd.read_csv(base + "MFN_KAZ_2016.CSV")
df5  = pd.read_csv(base + "MFN_KAZ_2017.CSV")
df6  = pd.read_csv(base + "MFN_KAZ_2018.CSV")
df7  = pd.read_csv(base + "MFN_KAZ_2019.CSV")
df8  = pd.read_csv(base + "MFN_KAZ_2020.CSV")
df9  = pd.read_csv(base + "MFN_KAZ_2021.CSV")
df10 = pd.read_csv(base + "MFN_KAZ_2022.CSV")
df11 = pd.read_csv(base + "MFN_KAZ_2023.CSV")

In [8]:
import re

dfs = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11]

kaz_mfn_raw = []
for d in dfs:
    tmp = d.copy()  # keep ALL original columns
    tmp["importer"] = "KAZ"
    tmp["hs6"] = tmp["ProductCode"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(6)
    tmp["year"] = tmp["Year"]
    tmp["mfn"] = pd.to_numeric(tmp["SimpleAverage"], errors="coerce") / 100.0  # percent -> fraction
    kaz_mfn_raw.append(tmp)

kaz_mfn_raw = pd.concat(kaz_mfn_raw, ignore_index=True)
kaz_mfn_raw.head()

,NomenCode,Reporter_ISO_N,Year,ProductCode,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,Nbr_NA_Lines,Nbr_Free_Lines,Nbr_AVE_Lines,Nbr_Dutiable_Lines,TotalNoOfValidLines,TotalNoOfLines,importer,hs6,year,mfn
0,H4,398,2013,10121,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,KAZ,010121,2013,0.00
1,H4,398,2013,10129,10.0,5.0,5.0,5.0,0.0,0.0,0.0,2.0,2.0,2.0,KAZ,010129,2013,0.05
2,H4,398,2013,10130,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,KAZ,010130,2013,0.05
3,H4,398,2013,10190,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,KAZ,010190,2013,0.05
4,H4,398,2013,10221,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,3.0,KAZ,010221,2013,0.00

In [4]:
kaz_mfn_raw.drop(['Sum_Of_Rates','Min_Rate','Max_Rate','SimpleAverage','Nbr_NA_Lines','Nbr_Free_Lines',
                 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines','TotalNoOfValidLines','TotalNoOfLines'],axis=1,inplace=True)
kaz_mfn_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,importer,hs6,year,mfn
0,H4,398,2013,10121,KAZ,010121,2013,0.00
1,H4,398,2013,10129,KAZ,010129,2013,0.05
2,H4,398,2013,10130,KAZ,010130,2013,0.05
3,H4,398,2013,10190,KAZ,010190,2013,0.05
4,H4,398,2013,10221,KAZ,010221,2013,0.00
...,...,...,...,...,...,...,...,...
58981,H6,398,2023,970529,KAZ,970529,2023,0.00
58982,H6,398,2023,970531,KAZ,970531,2023,0.00
58983,H6,398,2023,970539,KAZ,970539,2023,0.00
58984,H6,398,2023,970610,KAZ,970610,2023,0.00
58985,H6,398,2023,970690,KAZ,970690,2023,0.00

In [6]:
base = "kazakhstan/mfn ave/"   # change if needed

dfA1  = pd.read_csv(base + "AVEMFN_KAZ_2013.CSV")
dfA2  = pd.read_csv(base + "AVEMFN_KAZ_2014.CSV")
dfA3  = pd.read_csv(base + "AVEMFN_KAZ_2015.CSV")
dfA4  = pd.read_csv(base + "AVEMFN_KAZ_2017.CSV")
dfA5  = pd.read_csv(base + "AVEMFN_KAZ_2018.CSV")
dfA6  = pd.read_csv(base + "AVEMFN_KAZ_2019.CSV")
dfA7  = pd.read_csv(base + "AVEMFN_KAZ_2020.CSV")
dfA8  = pd.read_csv(base + "AVEMFN_KAZ_2021.CSV")
dfA9 = pd.read_csv(base + "AVEMFN_KAZ_2022.CSV")
dfA10 = pd.read_csv(base + "AVEMFN_KAZ_2023.CSV")
dfA11  = pd.read_csv(base + "AVEMFN_KAZ_2016.CSV")

In [9]:
dfs_ave = [dfA1,dfA2,dfA3,dfA4,dfA5,dfA6,dfA7,dfA8,dfA9,dfA10,dfA11]

kaz_ave_raw = []
for d in dfs_ave:
    tmp = d.copy()  # keep ALL columns
    tmp["importer"] = "IND"
    tmp["hs6"] = tmp["ProductCode"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(6)
    tmp["year"] = tmp["Year"]
    tmp["mfn_ave"] = pd.to_numeric(tmp["SimpleAverage"], errors="coerce") / 100.0
    kaz_ave_raw.append(tmp)

kaz_ave_raw = pd.concat(kaz_ave_raw, ignore_index=True)
kaz_ave_raw.head()

,NomenCode,Reporter_ISO_N,Year,ProductCode,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,Nbr_NA_Lines,Nbr_Free_Lines,Nbr_AVE_Lines,Nbr_Dutiable_Lines,TotalNoOfValidLines,TotalNoOfLines,EstCode,importer,hs6,year,mfn_ave
0,H4,398,2013,10121,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,U2,IND,010121,2013,0.00
1,H4,398,2013,10129,10.0,5.0,5.0,5.0,0.0,0.0,0.0,2.0,2.0,2.0,U2,IND,010129,2013,0.05
2,H4,398,2013,10130,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,U2,IND,010130,2013,0.05
3,H4,398,2013,10190,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,U2,IND,010190,2013,0.05
4,H4,398,2013,10221,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,3.0,U2,IND,010221,2013,0.00

In [8]:
kaz_ave_raw.drop(['Sum_Of_Rates','Min_Rate','Max_Rate','SimpleAverage','Nbr_NA_Lines','Nbr_Free_Lines',
                 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines','TotalNoOfValidLines','TotalNoOfLines'],axis=1,inplace=True)
kaz_mfn_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,importer,hs6,year,mfn
0,H4,398,2013,10121,KAZ,010121,2013,0.00
1,H4,398,2013,10129,KAZ,010129,2013,0.05
2,H4,398,2013,10130,KAZ,010130,2013,0.05
3,H4,398,2013,10190,KAZ,010190,2013,0.05
4,H4,398,2013,10221,KAZ,010221,2013,0.00
...,...,...,...,...,...,...,...,...
58981,H6,398,2023,970529,KAZ,970529,2023,0.00
58982,H6,398,2023,970531,KAZ,970531,2023,0.00
58983,H6,398,2023,970539,KAZ,970539,2023,0.00
58984,H6,398,2023,970610,KAZ,970610,2023,0.00
58985,H6,398,2023,970690,KAZ,970690,2023,0.00

In [11]:
key = ["importer", "hs6", "year"]

# Merge (keep all columns from both; suffixes prevent name clashes)
kaz_mfn_combined = kaz_mfn_raw.merge(
    kaz_ave_raw,
    on=key,
    how="outer",
suffixes=("_rawMFN", "_rawMFNAVE")
)

# Add the two variables with the exact names you want
# (mfn already exists from raw MFN; mfn_ave exists from raw MFN+AVE)
kaz_mfn_combined["mfn"] = kaz_mfn_combined["mfn"]              # MFN tariff rate from raw MFN dataset
kaz_mfn_combined["mfnAVE"] = kaz_mfn_combined["mfn_ave"]       # AVE MFN from raw MFN+AVE dataset

# Optional quick check
kaz_mfn_combined.head()

,NomenCode_rawMFN,Reporter_ISO_N_rawMFN,Year_rawMFN,ProductCode_rawMFN,importer,hs6,year,mfn,NomenCode_rawMFNAVE,Reporter_ISO_N_rawMFNAVE,Year_rawMFNAVE,ProductCode_rawMFNAVE,EstCode,mfn_ave,mfnAVE
0,NaN,NaN,NaN,NaN,IND,010121,2013,NaN,H4,398.0,2013.0,10121.0,U2,0.0,0.0
1,NaN,NaN,NaN,NaN,IND,010121,2014,NaN,H4,398.0,2014.0,10121.0,U2,0.0,0.0
2,NaN,NaN,NaN,NaN,IND,010121,2015,NaN,H4,398.0,2015.0,10121.0,U2,0.0,0.0
3,NaN,NaN,NaN,NaN,IND,010121,2016,NaN,H4,398.0,2016.0,10121.0,U2,0.0,0.0
4,NaN,NaN,NaN,NaN,IND,010121,2017,NaN,H5,398.0,2017.0,10121.0,U2,0.0,0.0

In [14]:
kaz_mfn_raw.to_csv('kaz_mfn.csv')

In [10]:
import pandas as pd

base = "kazakhstan/pref/"   # change if needed


dfP1  = pd.read_csv(base + "PREF_KAZ_2014.CSV")
dfP2  = pd.read_csv(base + "PREF_KAZ_2015.CSV")
dfP3  = pd.read_csv(base + "PREF_KAZ_2016.CSV")
dfP4  = pd.read_csv(base + "PREF_KAZ_2017.CSV")
dfP5  = pd.read_csv(base + "PREF_KAZ_2018.CSV")
dfP6  = pd.read_csv(base + "PREF_KAZ_2019.CSV")
dfP7  = pd.read_csv(base + "PREF_KAZ_2020.CSV")
dfP8  = pd.read_csv(base + "PREF_KAZ_2021.CSV")
dfP9  = pd.read_csv(base + "PREF_KAZ_2022.CSV")
dfP10 = pd.read_csv(base + "PREF_KAZ_2023.CSV")
dfP11 = pd.read_csv(base + "PREF_KAZ_2013.CSV")

In [11]:
kaz_ave_raw.to_csv('kaz_mfnave.csv')

In [26]:
import pandas as pd

EXPORTER_COL = "Partner"   # <- CHANGE THIS to your actual exporter/partner column name


dfs_pref = [dfP1, dfP2, dfP3, dfP4, dfP5, dfP6, dfP7, dfP8, dfP9, dfP10,dfP11]

pref_raw = []
for d in dfs_pref:
    tmp = d.copy()  # keep ALL original columns
    tmp["importer"] = "IND"
    tmp["exporter"] = tmp[EXPORTER_COL].astype(str)

    tmp["hs6"] = tmp["ProductCode"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(6)
    tmp["year"] = tmp["Year"]

    # same as your MFN: SimpleAverage is in percent
    tmp["pref"] = pd.to_numeric(tmp["SimpleAverage"], errors="coerce") / 100.0
    pref_raw.append(tmp)

kaz_pref_raw = pd.concat(pref_raw, ignore_index=True)
kaz_pref_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,Partner,ExcludedFrom,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,TotalNoOfLines,Nbr_Pref_Lines,Nbr_MFN_Lines,Nbr_NA_Lines,importer,exporter,hs6,year,pref
0,H4,398,2014,110429,K51,,0.00,0.00,0.00,0.00,14,14,0,0,IND,K51,110429,2014,0.0000
1,H4,398,2014,110430,K51,,0.00,0.00,0.00,0.00,2,2,0,0,IND,K51,110430,2014,0.0000
2,H4,398,2014,110510,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110510,2014,0.0000
3,H4,398,2014,110520,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110520,2014,0.0000
4,H4,398,2014,110610,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110610,2014,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197956,H4,398,2013,262091,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262091,2013,0.0375
197957,H4,398,2013,262099,G27,,26.25,0.00,3.75,2.92,9,7,2,0,IND,G27,262099,2013,0.0292
197958,H4,398,2013,262110,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262110,2013,0.0375
197959,H4,398,2013,262190,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262190,2013,0.0375
197960,H4,398,2013,320190,G27,,3.75,0.00,3.75,1.88,2,1,1,0,IND,G27,320190,2013,0.0188

In [27]:
dfPA1  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2013.CSV")
dfPA3  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2014.CSV")
dfPA4  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2015.CSV")
dfPA5  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2016.CSV")
dfPA6  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2017.CSV")
dfPA7  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2018.CSV")
dfPA8  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2019.CSV")
dfPA9  = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2020.CSV")
dfPA10 = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2021.CSV")
dfPA11 = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2022.CSV")
dfPA12 = pd.read_csv("kazakhstan/pref ave/AVEPref_KAZ_2023.CSV")

dfs_pref_ave = [dfPA1, dfPA3, dfPA4, dfPA5, dfPA6, dfPA7, dfPA8, dfPA9, dfPA10, dfPA11, dfPA12]

pref_ave_raw = []
for d in dfs_pref_ave:
    tmp = d.copy()  # keep ALL original columns
    tmp["importer"] = "IND"
    tmp["exporter"] = tmp[EXPORTER_COL].astype(str)

    tmp["hs6"] = tmp["ProductCode"].astype(str).str.replace(r"\D", "", regex=True).str.zfill(6)
    tmp["year"] = tmp["Year"]

    tmp["pref_ave"] = pd.to_numeric(tmp["SimpleAverage"], errors="coerce") / 100.0
    pref_ave_raw.append(tmp)

kaz_pref_ave_raw = pd.concat(pref_ave_raw, ignore_index=True)
kaz_pref_ave_raw.head()

,NomenCode,Reporter_ISO_N,Year,ProductCode,Partner,ExcludedFrom,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,TotalNoOfLines,Nbr_Pref_Lines,Nbr_MFN_Lines,Nbr_NA_Lines,EstCode,importer,exporter,hs6,year,pref_ave
0,H4,398,2013,10129,K51,,0.0,0.0,0.0,0.0,2,2,0,0,U2,IND,K51,010129,2013,0.0
1,H4,398,2013,10129,N80,,0.0,0.0,0.0,0.0,2,2,0,0,U2,IND,N80,010129,2013,0.0
2,H4,398,2013,10130,N80,,0.0,0.0,0.0,0.0,1,1,0,0,U2,IND,N80,010130,2013,0.0
3,H4,398,2013,10130,K51,,0.0,0.0,0.0,0.0,1,1,0,0,U2,IND,K51,010130,2013,0.0
4,H4,398,2013,10190,K51,,0.0,0.0,0.0,0.0,1,1,0,0,U2,IND,K51,010190,2013,0.0

In [28]:
kaz_pref_ave_raw.drop(['ExcludedFrom','Sum_Of_Rates','Min_Rate','Max_Rate','SimpleAverage','TotalNoOfLines','Nbr_Pref_Lines',
                       'Nbr_MFN_Lines','Nbr_NA_Lines','EstCode','Partner'],axis=1, inplace=True)
kaz_pref_ave_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,importer,exporter,hs6,year,pref_ave
0,H4,398,2013,10129,IND,K51,010129,2013,0.0000
1,H4,398,2013,10129,IND,N80,010129,2013,0.0000
2,H4,398,2013,10130,IND,N80,010130,2013,0.0000
3,H4,398,2013,10130,IND,K51,010130,2013,0.0000
4,H4,398,2013,10190,IND,K51,010190,2013,0.0000
...,...,...,...,...,...,...,...,...,...
197956,H6,398,2023,961900,IND,B32,961900,2023,0.0000
197957,H6,398,2023,962000,IND,02D,962000,2023,0.0606
197958,H6,398,2023,962000,IND,A50,962000,2023,0.0000
197959,H6,398,2023,962000,IND,688,962000,2023,0.0000
197960,H6,398,2023,962000,IND,B32,962000,2023,0.0000

In [29]:
kaz_pref_ave_raw.to_csv('kaz_AVEpref.csv')

In [30]:
kaz_pref_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,Partner,ExcludedFrom,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,TotalNoOfLines,Nbr_Pref_Lines,Nbr_MFN_Lines,Nbr_NA_Lines,importer,exporter,hs6,year,pref
0,H4,398,2014,110429,K51,,0.00,0.00,0.00,0.00,14,14,0,0,IND,K51,110429,2014,0.0000
1,H4,398,2014,110430,K51,,0.00,0.00,0.00,0.00,2,2,0,0,IND,K51,110430,2014,0.0000
2,H4,398,2014,110510,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110510,2014,0.0000
3,H4,398,2014,110520,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110520,2014,0.0000
4,H4,398,2014,110610,K51,,0.00,0.00,0.00,0.00,1,1,0,0,IND,K51,110610,2014,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197956,H4,398,2013,262091,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262091,2013,0.0375
197957,H4,398,2013,262099,G27,,26.25,0.00,3.75,2.92,9,7,2,0,IND,G27,262099,2013,0.0292
197958,H4,398,2013,262110,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262110,2013,0.0375
197959,H4,398,2013,262190,G27,,3.75,3.75,3.75,3.75,1,1,0,0,IND,G27,262190,2013,0.0375
197960,H4,398,2013,320190,G27,,3.75,0.00,3.75,1.88,2,1,1,0,IND,G27,320190,2013,0.0188

In [31]:
kaz_pref_raw.drop(['ExcludedFrom','Sum_Of_Rates','Min_Rate','Max_Rate','SimpleAverage','TotalNoOfLines','Nbr_Pref_Lines',
                       'Nbr_MFN_Lines','Nbr_NA_Lines','Partner'],axis=1, inplace=True)
kaz_pref_raw

,NomenCode,Reporter_ISO_N,Year,ProductCode,importer,exporter,hs6,year,pref
0,H4,398,2014,110429,IND,K51,110429,2014,0.0000
1,H4,398,2014,110430,IND,K51,110430,2014,0.0000
2,H4,398,2014,110510,IND,K51,110510,2014,0.0000
3,H4,398,2014,110520,IND,K51,110520,2014,0.0000
4,H4,398,2014,110610,IND,K51,110610,2014,0.0000
...,...,...,...,...,...,...,...,...,...
197956,H4,398,2013,262091,IND,G27,262091,2013,0.0375
197957,H4,398,2013,262099,IND,G27,262099,2013,0.0292
197958,H4,398,2013,262110,IND,G27,262110,2013,0.0375
197959,H4,398,2013,262190,IND,G27,262190,2013,0.0375
197960,H4,398,2013,320190,IND,G27,320190,2013,0.0188

In [32]:
kaz_pref_raw.to_csv('kaz_pref.csv')

In [3]:
import pandas as pd
import os

# 1. Setup the directory structure
# Note: 'mfn ave' and 'pref ave' contain spaces as per your last message
base_path = "kazakhstan"
folders = {
    "MFN": "mfn",
    "MFN_AVE": "mfn ave",
    "PREF": "pref",
    "PREF_AVE": "pref ave"
}

# 2. Define standard WITS file prefixes for Kazakhstan
# Standard MFN: MFN_KAZ_... | AVE MFN: AVEMFN_KAZ_... 
# Standard Pref: Pref_KAZ_... | AVE Pref: AVEPref_KAZ_...
prefixes = {
    "MFN": "MFN_KAZ_",
    "MFN_AVE": "AVEMFN_KAZ_",
    "PREF": "Pref_KAZ_",
    "PREF_AVE": "AVEPref_KAZ_"
}

years = range(2013, 2024)

def merge_wits_files(category):
    all_data = []
    folder = folders[category]
    prefix = prefixes[category]
    
    print(f"--- Merging {category} ---")
    
    for year in years:
        file_path = f"{base_path}/{folder}/{prefix}{year}.CSV"
        
        if os.path.exists(file_path):
            try:
                # low_memory=False ensures that mixed data types (common in WITS) 
                # don't trigger warnings or errors.
                df = pd.read_csv(file_path, low_memory=False)
                
                # Critical step for Teti/Fontagne: Strip hidden spaces from headers
                # so that columns like 'ProductCode ' become 'ProductCode'
                df.columns = df.columns.str.strip()
                
                all_data.append(df)
                print(f"Added: {year}")
            except Exception as e:
                print(f"Error reading {year}: {e}")
        else:
            print(f"Missing: {file_path}")
            
    if all_data:
        # sort=False ensures we keep the original column order from the files
        merged_df = pd.concat(all_data, axis=0, ignore_index=True, sort=False)
        print(f"Final {category} dataset shape: {merged_df.shape}")
        return merged_df
    else:
        print(f"No data found for {category}")
        return pd.DataFrame()

# 3. Execute the merge
df_mfn = merge_wits_files("MFN")
df_mfn_ave = merge_wits_files("MFN_AVE")
df_pref = merge_wits_files("PREF")
df_pref_ave = merge_wits_files("PREF_AVE")

# 4. Check if ProductCode needs cleaning (sometimes exported with ' marks)
def clean_product_codes(df):
    if not df.empty and 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.zfill(6)
    return df

df_mfn = clean_product_codes(df_mfn)
df_mfn_ave = clean_product_codes(df_mfn_ave)
df_pref = clean_product_codes(df_pref)
df_pref_ave = clean_product_codes(df_pref_ave)

--- Merging MFN ---
Added: 2013
Added: 2014
Added: 2015
Added: 2016
Added: 2017
Added: 2018
Added: 2019
Added: 2020
Added: 2021
Added: 2022
Added: 2023
Final MFN dataset shape: (58986, 14)
--- Merging MFN_AVE ---
Added: 2013
Added: 2014
Added: 2015
Added: 2016
Added: 2017
Added: 2018
Added: 2019
Added: 2020
Added: 2021
Added: 2022
Added: 2023
Final MFN_AVE dataset shape: (58986, 15)
--- Merging PREF ---
Added: 2013
Added: 2014
Added: 2015
Added: 2016
Added: 2017
Added: 2018
Added: 2019
Added: 2020
Added: 2021
Added: 2022
Added: 2023
Final PREF dataset shape: (197961, 14)
--- Merging PREF_AVE ---
Added: 2013
Added: 2014
Added: 2015
Added: 2016
Added: 2017
Added: 2018
Added: 2019
Added: 2020
Added: 2021
Added: 2022
Added: 2023
Final PREF_AVE dataset shape: (197961, 15)

In [4]:
# Display the first 5 rows of the MFN dataset
print("MFN Dataset (Top):")
display(df_mfn.head())

# Display the first 5 rows of the Preferential dataset
print("Preferential Dataset (Top):")
display(df_pref.head())

MFN Dataset (Top):

,NomenCode,Reporter_ISO_N,Year,ProductCode,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,Nbr_NA_Lines,Nbr_Free_Lines,Nbr_AVE_Lines,Nbr_Dutiable_Lines,TotalNoOfValidLines,TotalNoOfLines
0,H4,398,2013,010121,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,H4,398,2013,010129,10.0,5.0,5.0,5.0,0.0,0.0,0.0,2.0,2.0,2.0
2,H4,398,2013,010130,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0
3,H4,398,2013,010190,5.0,5.0,5.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0
4,H4,398,2013,010221,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,3.0

Preferential Dataset (Top):

,NomenCode,Reporter_ISO_N,Year,ProductCode,Partner,ExcludedFrom,Sum_Of_Rates,Min_Rate,Max_Rate,SimpleAverage,TotalNoOfLines,Nbr_Pref_Lines,Nbr_MFN_Lines,Nbr_NA_Lines
0,H4,398,2013,081090,N80,,0.0,0.0,0.0,0.0,2,1,1,0
1,H4,398,2013,081110,N80,,0.0,0.0,0.0,0.0,3,3,0,0
2,H4,398,2013,081120,N80,,0.0,0.0,0.0,0.0,7,7,0,0
3,H4,398,2013,081190,N80,,0.0,0.0,0.0,0.0,10,10,0,0
4,H4,398,2013,081210,N80,,0.0,0.0,0.0,0.0,1,1,0,0

In [7]:
print("MFN AVE Metadata and Structure:")
df_pref.info()

MFN AVE Metadata and Structure:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197961 entries, 0 to 197960
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   NomenCode       197961 non-null  object
 1   Reporter_ISO_N  197961 non-null  int64
 2   Year            197961 non-null  int64
 3   ProductCode     197961 non-null  object
 4   Partner         197961 non-null  object
 5   ExcludedFrom    197961 non-null  object
 6   Sum_Of_Rates    196387 non-null  float64
 7   Min_Rate        196387 non-null  float64
 8   Max_Rate        196387 non-null  float64
 9   SimpleAverage   196387 non-null  float64
 10  TotalNoOfLines  197961 non-null  int64
 11  Nbr_Pref_Lines  197961 non-null  int64
 12  Nbr_MFN_Lines   197961 non-null  int64
 13  Nbr_NA_Lines    197961 non-null  int64
dtypes: float64(4), int64(6), object(4)
memory usage: 21.1+ MB

In [11]:
# 1. Define the columns to drop (handling the typo 'Min_RateMax_Rate' as two columns)
cols_to_drop = [
    'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 
    'Nbr_Free_Lines', 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 
    'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode'
]

# 2. Clean MFN and MFN AVE
print("Cleaning MFN datasets...")
# Prepare MFN (Non-AVE)
df_mfn = df_mfn.rename(columns={'SimpleAverage': 'mfn'})
df_mfn = df_mfn.drop(columns=[c for c in cols_to_drop if c in df_mfn.columns], errors='ignore')

# Prepare MFN AVE
df_mfn_ave = df_mfn_ave.rename(columns={'SimpleAverage': 'mfnAVE'})
# We keep 'EstCode' in AVE files as it is often used in the Fontagné methodology
df_mfn_ave = df_mfn_ave.drop(columns=[c for c in cols_to_drop if c in df_mfn_ave.columns], errors='ignore')

# 3. Clean Pref and Pref AVE
print("Cleaning Preferential datasets...")
# Prepare Pref (Non-AVE)
df_pref = df_pref.rename(columns={'SimpleAverage': 'pref'})
df_pref = df_pref.drop(columns=[c for c in cols_to_drop if c in df_pref.columns + ['ExcludedFrom']], errors='ignore')

# Prepare Pref AVE
df_pref_ave = df_pref_ave.rename(columns={'SimpleAverage': 'prefAVE'})
df_pref_ave = df_pref_ave.drop(columns=[c for c in cols_to_drop if c in df_pref_ave.columns + ['ExcludedFrom']], errors='ignore')

# 4. Perform the Merges
print("Merging cleaned datasets...")

# Merge MFN: dimensions are Importer (Reporter_ISO_N), HS6 (ProductCode), and Year
df_mfn_combined = pd.merge(
    df_mfn, 
    df_mfn_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode'], 
    how='outer'
)

# Merge Pref: dimensions are Importer, Partner, HS6, and Year
df_pref_combined = pd.merge(
    df_pref, 
    df_pref_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], 
    how='outer'
)

# 5. Final Display
print("\n--- Success: Merged and Cleaned ---")
print(f"MFN Combined Columns: {df_mfn_combined.columns.tolist()}")
print(f"Pref Combined Columns: {df_pref_combined.columns.tolist()}")

display(df_mfn_combined.head())

Cleaning MFN datasets...
Cleaning Preferential datasets...
Merging cleaned datasets...

--- Success: Merged and Cleaned ---
MFN Combined Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE', 'EstCode']
Pref Combined Columns: ['NomenCode_x', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Partner', 'ExcludedFrom_x', 'Sum_Of_Rates_x', 'Min_Rate_x', 'Max_Rate_x', 'pref', 'TotalNoOfLines_x', 'Nbr_Pref_Lines_x', 'Nbr_MFN_Lines_x', 'Nbr_NA_Lines_x', 'NomenCode_y', 'ExcludedFrom_y', 'Sum_Of_Rates_y', 'Min_Rate_y', 'Max_Rate_y', 'prefAVE', 'TotalNoOfLines_y', 'Nbr_Pref_Lines_y', 'Nbr_MFN_Lines_y', 'Nbr_NA_Lines_y', 'EstCode']

   Reporter_ISO_N  Year ProductCode  mfn  mfnAVE EstCode
0             398  2013      010121  0.0     0.0     U2
1             398  2013      010129  5.0     5.0     U2
2             398  2013      010130  5.0     5.0     U2
3             398  2013      010190  5.0     5.0     U2
4             398  2013      010221  0.0     0.0     U2

In [12]:
import pandas as pd

# --- 1. PREFERENTIAL DATASETS ---
# Rename SimpleAverage before merging to create the variables you need
df_pref = df_pref.rename(columns={'SimpleAverage': 'pref'})
df_pref_ave = df_pref_ave.rename(columns={'SimpleAverage': 'prefAVE'})

# Outer Merge on dimensions: Importer, Partner (Tariff Schedule), HS6, and Year
df_pref_combined = pd.merge(
    df_pref, 
    df_pref_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], 
    how='outer'
)

# Drop the specific columns you listed
pref_drop_list = [
    'ExcludedFrom_x', 'Sum_Of_Rates_x', 'Min_Rate_x', 'Max_Rate_x', 
    'TotalNoOfLines_x', 'Nbr_Pref_Lines_x', 'Nbr_MFN_Lines_x', 'Nbr_NA_Lines_x', 
    'NomenCode_y', 'ExcludedFrom_y', 'Sum_Of_Rates_y', 'Min_Rate_y', 
    'Max_Rate_y', 'TotalNoOfLines_y', 'Nbr_Pref_Lines_y', 'Nbr_MFN_Lines_y', 
    'Nbr_NA_Lines_y', 'EstCode'
]
df_pref_combined = df_pref_combined.drop(columns=pref_drop_list, errors='ignore')

# --- 2. MFN DATASETS ---
# Apply the same logic for the MFN pair
df_mfn = df_mfn.rename(columns={'SimpleAverage': 'mfn'})
df_mfn_ave = df_mfn_ave.rename(columns={'SimpleAverage': 'mfnAVE'})

# Outer Merge on dimensions: Importer, HS6, and Year
df_mfn_combined = pd.merge(
    df_mfn, 
    df_mfn_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode'], 
    how='outer'
)

# Clean MFN metadata (following the same pattern as your Pref list)
mfn_drop_list = [
    'Sum_Of_Rates_x', 'Min_Rate_x', 'Max_Rate_x', 'Nbr_NA_Lines_x', 
    'Nbr_Free_Lines_x', 'Nbr_AVE_Lines_x', 'Nbr_Dutiable_Lines_x', 
    'TotalNoOfValidLines_x', 'TotalNoOfLines_x', 'NomenCode_y',
    'Sum_Of_Rates_y', 'Min_Rate_y', 'Max_Rate_y', 'Nbr_NA_Lines_y', 
    'Nbr_Free_Lines_y', 'Nbr_AVE_Lines_y', 'Nbr_Dutiable_Lines_y', 
    'TotalNoOfValidLines_y', 'TotalNoOfLines_y', 'EstCode'
]
df_mfn_combined = df_mfn_combined.drop(columns=mfn_drop_list, errors='ignore')

# --- 3. VERIFICATION ---
print("--- Datasets Finalized ---")
print(f"Preferential Columns: {df_pref_combined.columns.tolist()}")
print(f"MFN Columns: {df_mfn_combined.columns.tolist()}")

# Ensure ProductCode is clean (no quotes) and 6-digits
for df in [df_pref_combined, df_mfn_combined]:
    df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.zfill(6)

display(df_pref_combined.head())

--- Datasets Finalized ---
Preferential Columns: ['NomenCode_x', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Partner', 'pref', 'prefAVE']
MFN Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE']

  NomenCode_x  Reporter_ISO_N  Year ProductCode Partner  pref  prefAVE
0          H4             398  2013      010129     K51   0.0      0.0
1          H4             398  2013      010129     N80   0.0      0.0
2          H4             398  2013      010130     K51   0.0      0.0
3          H4             398  2013      010130     N80   0.0      0.0
4          H4             398  2013      010190     K51   0.0      0.0

In [ ]:
import pandas as pd

# 1. Define the columns to drop from all datasets
# Based on your list: metadata, counts, and calculated limits
common_drop = [
    'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 
    'Nbr_NA_Lines', 'Nbr_Free_Lines', 'Nbr_AVE_Lines', 
    'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines'
]

# 2. Process MFN Datasets
print("Processing MFN pair...")
# Rename SimpleAverage and Drop metadata from MFN
df_mfn = df_mfn.rename(columns={'SimpleAverage': 'mfn'})
df_mfn = df_mfn.drop(columns=common_drop, errors='ignore')

# Rename SimpleAverage and Drop metadata + EstCode from MFN AVE
df_mfn_ave = df_mfn_ave.rename(columns={'SimpleAverage': 'mfnAVE'})
df_mfn_ave = df_mfn_ave.drop(columns=common_drop + ['EstCode'], errors='ignore')

# Merge MFN pair
# We include NomenCode in the join keys so we only keep one copy
df_mfn_combined = pd.merge(
    df_mfn, 
    df_mfn_ave, 
    on=['NomenCode', 'Reporter_ISO_N', 'Year', 'ProductCode'], 
    how='outer'
)

# 3. Process PREFERENTIAL Datasets
print("Processing Preferential pair...")
# Columns specific to the preferential datasets
pref_extra_drop = ['ExcludedFrom', 'Nbr_Pref_Lines', 'Nbr_MFN_Lines']

# Prepare Pref
df_pref = df_pref.rename(columns={'SimpleAverage': 'pref'})
df_pref = df_pref.drop(columns=common_drop + pref_extra_drop, errors='ignore')

# Prepare Pref AVE
df_pref_ave = df_pref_ave.rename(columns={'SimpleAverage': 'prefAVE'})
df_pref_ave = df_pref_ave.drop(columns=common_drop + pref_extra_drop + ['EstCode'], errors='ignore')

# Merge Preferential pair
# Join keys include 'Partner' as the tariff schedule dimension
df_pref_combined = pd.merge(
    df_pref, 
    df_pref_ave, 
    on=['NomenCode', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], 
    how='outer'
)

# 4. Final Verification
print("\n--- Phase 1 Finalized ---")
print(f"MFN Combined Columns: {df_mfn_combined.columns.tolist()}")
print(f"Preferential Combined Columns: {df_pref_combined.columns.tolist()}")

# Display the first few rows of your new primary datasets
display(df_mfn_combined.head())
display(df_pref_combined.head())

In [13]:
import pandas as pd

# 1. Merge the MFN pair
# Dimensions: Importer (Reporter_ISO_N), Year, and Product (ProductCode)
print("Creating Master MFN Dataset...")
df_mfn_combined = pd.merge(
    df_mfn, 
    df_mfn_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode'], 
    how='outer'
)

# 2. Merge the Preferential pair
# Dimensions: Importer, Year, Product, and Partner (Exporter/Tariff Schedule)
print("Creating Master Preferential Dataset...")
df_pref_combined = pd.merge(
    df_pref, 
    df_pref_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], 
    how='outer'
)

# 3. Clean ProductCode (Crucial for Teti/Fontagne)
# Ensure ProductCode is a 6-digit string to fix leading zeros (e.g., '010121')
for df in [df_mfn_combined, df_pref_combined]:
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.zfill(6)

# 4. Final Display and Verification
print("\n--- Master Datasets Ready ---")
print(f"MFN Combined: {df_mfn_combined.shape[0]} rows | Columns: {df_mfn_combined.columns.tolist()}")
print(f"Pref Combined: {df_pref_combined.shape[0]} rows | Columns: {df_pref_combined.columns.tolist()}")

print("\nMFN Sample:")
display(df_mfn_combined.head())
print("\nPreferential Sample:")
display(df_pref_combined.head())

Creating Master MFN Dataset...
Creating Master Preferential Dataset...

--- Master Datasets Ready ---
MFN Combined: 58986 rows | Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE', 'EstCode']
Pref Combined: 197961 rows | Columns: ['NomenCode_x', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Partner', 'ExcludedFrom_x', 'Sum_Of_Rates_x', 'Min_Rate_x', 'Max_Rate_x', 'pref', 'TotalNoOfLines_x', 'Nbr_Pref_Lines_x', 'Nbr_MFN_Lines_x', 'Nbr_NA_Lines_x', 'NomenCode_y', 'ExcludedFrom_y', 'Sum_Of_Rates_y', 'Min_Rate_y', 'Max_Rate_y', 'prefAVE', 'TotalNoOfLines_y', 'Nbr_Pref_Lines_y', 'Nbr_MFN_Lines_y', 'Nbr_NA_Lines_y', 'EstCode']

MFN Sample:

   Reporter_ISO_N  Year ProductCode  mfn  mfnAVE EstCode
0             398  2013      010121  0.0     0.0     U2
1             398  2013      010129  5.0     5.0     U2
2             398  2013      010130  5.0     5.0     U2
3             398  2013      010190  5.0     5.0     U2
4             398  2013      010221  0.0     0.0     U2

Preferential Sample:

,NomenCode_x,Reporter_ISO_N,Year,ProductCode,Partner,ExcludedFrom_x,Sum_Of_Rates_x,Min_Rate_x,Max_Rate_x,pref,...,ExcludedFrom_y,Sum_Of_Rates_y,Min_Rate_y,Max_Rate_y,prefAVE,TotalNoOfLines_y,Nbr_Pref_Lines_y,Nbr_MFN_Lines_y,Nbr_NA_Lines_y,EstCode
0,H4,398,2013,010129,K51,,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,0.0,2,2,0,0,U2
1,H4,398,2013,010129,N80,,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,0.0,2,2,0,0,U2
2,H4,398,2013,010130,K51,,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,0.0,1,1,0,0,U2
3,H4,398,2013,010130,N80,,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,0.0,1,1,0,0,U2
4,H4,398,2013,010190,K51,,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,0.0,1,1,0,0,U2

In [15]:
import pandas as pd

# 1. Define the exact lists of columns to drop for each category
# This removes all metadata and keeps only dimensions and the tariff rate
mfn_drop = [
    'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 
    'Nbr_Free_Lines', 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 
    'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode'
]

pref_drop = [
    'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 
    'TotalNoOfLines', 'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 
    'NomenCode', 'ExcludedFrom'
]

# 2. Clean Individual Datasets PRE-MERGE
print("Cleaning individual dataframes...")

# MFN
df_mfn = df_mfn.rename(columns={'SimpleAverage': 'mfn'})
df_mfn = df_mfn.drop(columns=[c for c in mfn_drop if c in df_mfn.columns], errors='ignore')

# MFN AVE
df_mfn_ave = df_mfn_ave.rename(columns={'SimpleAverage': 'mfnAVE'})
df_mfn_ave = df_mfn_ave.drop(columns=[c for c in mfn_drop if c in df_mfn_ave.columns] + ['EstCode'], errors='ignore')

# Pref
df_pref = df_pref.rename(columns={'SimpleAverage': 'pref'})
df_pref = df_pref.drop(columns=[c for c in pref_drop if c in df_pref.columns], errors='ignore')

# Pref AVE
df_pref_ave = df_pref_ave.rename(columns={'SimpleAverage': 'prefAVE'})
df_pref_ave = df_pref_ave.drop(columns=[c for c in pref_drop if c in df_pref_ave.columns] + ['EstCode'], errors='ignore')

# 3. Perform the Final Outer Merges
print("Merging cleaned datasets...")

# Final MFN Dataset
df_mfn_combined = pd.merge(
    df_mfn, 
    df_mfn_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode'], 
    how='outer'
)

# Final Preferential Dataset
df_pref_combined = pd.merge(
    df_pref, 
    df_pref_ave, 
    on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], 
    how='outer'
)

# 4. Final Cleanup of ProductCode
# Ensuring HS6 codes are 6-digit strings (crucial for Teti/Fontagne matching)
for df in [df_mfn_combined, df_pref_combined]:
    df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.zfill(6)

# 5. Verification
print("\n--- Process Complete ---")
print(f"MFN Combined Columns: {df_mfn_combined.columns.tolist()}")
print(f"Pref Combined Columns: {df_pref_combined.columns.tolist()}")

display(df_mfn_combined.head())
display(df_pref_combined.head())

Cleaning individual dataframes...
Merging cleaned datasets...

--- Process Complete ---
MFN Combined Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE']
Pref Combined Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner', 'pref', 'prefAVE']

   Reporter_ISO_N  Year ProductCode  mfn  mfnAVE
0             398  2013      010121  0.0     0.0
1             398  2013      010129  5.0     5.0
2             398  2013      010130  5.0     5.0
3             398  2013      010190  5.0     5.0
4             398  2013      010221  0.0     0.0

   Reporter_ISO_N  Year ProductCode Partner  pref  prefAVE
0             398  2013      010129     K51   0.0      0.0
1             398  2013      010129     N80   0.0      0.0
2             398  2013      010130     K51   0.0      0.0
3             398  2013      010130     N80   0.0      0.0
4             398  2013      010190     K51   0.0      0.0

In [18]:
import pandas as pd

# 1. Load the country list with flexible delimiter detection
country_list = pd.read_csv('country_list.csv', sep=None, engine='python', on_bad_lines='skip')

# 2. Clean headers (remove spaces/quotes) and find the right columns dynamically
country_list.columns = country_list.columns.str.strip().str.replace(' ', '')

# Identify the columns even if named slightly differently
# Usually 'CountryCode' and 'ISO3'
code_col = [c for c in country_list.columns if 'CountryCode' in c or 'Code' in c][0]
iso_col = [c for c in country_list.columns if 'ISO3' in c][0]

print(f"Using columns: {code_col} for numerical codes and {iso_col} for ISO3")

# 3. Create a clean mapping dictionary
iso_map_dict = country_list.set_index(code_col)[iso_col].to_dict()

# 4. Map the numerical codes to WITS-ISO3 in the MFN dataset
df_mfn_combined['iso3_wits'] = df_mfn_combined['Reporter_ISO_N'].map(iso_map_dict)

# 5. Define Teti's Official ISO3 Correction Map
# These convert WITS non-standard codes to official ISO 3166-1 alpha-3
iso_correction_map = {
    'ROM': 'ROU', # Romania
    'ZAR': 'COD', # DR Congo
    'TMP': 'TLS', # Timor-Leste
    'SUD': 'SDN', # Sudan
    'SAM': 'WSM', # Samoa
    'SER': 'SRB', # Serbia
    'MNE': 'MNE', # Montenegro
    'ANT': 'CUW', # Netherlands Antilles
    'WLF': 'WLF', # Wallis and Futuna
    'SVK': 'SVK', # Slovakia
}

# 6. Final Conversion to Official ISO3
df_mfn_combined['iso3_reporter'] = df_mfn_combined['iso3_wits'].replace(iso_correction_map)

# 7. Clean up: Drop the intermediate WITS-ISO3 column
df_mfn_combined = df_mfn_combined.drop(columns=['iso3_wits'])

# Verification
print("\n--- MFN ISO Mapping Complete ---")
print(df_mfn_combined[['Reporter_ISO_N', 'iso3_reporter']].drop_duplicates().head())

Using columns: CountryCode for numerical codes and ﻿ISO3 for ISO3

--- MFN ISO Mapping Complete ---
   Reporter_ISO_N iso3_reporter
0             398           KAZ

In [23]:
import pandas as pd

# 1. Load Country List with Debugging
# Using latin1 to handle special characters and sep=None to guess the delimiter
cl = pd.read_csv('country_list.csv', sep=None, engine='python', encoding='latin1', on_bad_lines='skip')

# Strip any whitespace from headers to avoid "Column not found" errors
cl.columns = cl.columns.str.strip()

print("I found these columns in your country_list.csv:", cl.columns.tolist())

# 2. Assign column names based on what WITS usually provides
# We'll try to find the numerical code column and the ISO3 column
# If these fail, check the printout above and replace the strings in [''] below
num_code_col = [c for c in cl.columns if 'Code' in c][0]
iso3_col = [c for c in cl.columns if 'ISO3' in c or 'ISO' in c][0]

# 3. Define the Conversion Maps
# Step A: Numerical -> WITS ISO3
wits_iso_map = cl.set_index(num_code_col)[iso3_col].to_dict()

# Step B: WITS ISO3 -> Official ISO3 (Teti's correction list)
official_iso_map = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

# 4. Map the MFN dataset
# Create a temporary wits-iso column, then convert to official
df_mfn_combined['iso3_reporter'] = df_mfn_combined['Reporter_ISO_N'].map(wits_iso_map)
df_mfn_combined['iso3_reporter'] = df_mfn_combined['iso3_reporter'].replace(official_iso_map)

print("\n--- MFN ISO Mapping Complete ---")
print(df_mfn_combined[['Reporter_ISO_N', 'iso3_reporter']].drop_duplicates())

I found these columns in your country_list.csv: ['ï»¿ISO3', 'CountryCode', 'Country Name']

--- MFN ISO Mapping Complete ---
   Reporter_ISO_N iso3_reporter
0             398           KAZ

In [25]:
import pandas as pd
import numpy as np

# --- 1. Load Reference Files ---
# Country List (Semicolon delimited)
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin1')
cl.columns = cl.columns.str.strip()

# Preference Beneficiaries (Comma delimited)
pb = pd.read_csv('preference_beneficials.csv', encoding='latin1')
pb.columns = pb.columns.str.strip()

# --- 2. Build the Official ISO Mapping Dictionary ---
# Teti's correction map for non-standard WITS codes
iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

# Create a mapping from Numerical Code (string padded) to Official ISO3
cl['CountryCode_str'] = cl['CountryCode'].astype(str).str.zfill(3)
# First map Numerical -> WITS ISO3
wits_iso_dict = cl.set_index('CountryCode_str')['ISO3'].to_dict()

def to_official_iso(num_code):
    num_str = str(int(num_code)).zfill(3)
    wits_iso = wits_iso_dict.get(num_str)
    # Apply Teti corrections if applicable
    return iso_correction.get(wits_iso, wits_iso)

# --- 3. MFN ISO Mapping ---
print("Mapping MFN reporters to Official ISO3...")
df_mfn_combined['iso3_reporter'] = df_mfn_combined['Reporter_ISO_N'].apply(to_official_iso)

# --- 4. Preferential Bilateral Disaggregation ---
print("Disaggregating preferential schedules to individual exporters...")

# Merge dataset with beneficiaries
# RegionCode in pb matches 'Partner' (the schedule) in your dataset
# 'Partner' in pb is the numerical code of the beneficiary country
df_pref_bilateral = pd.merge(
    df_pref_combined,
    pb[['RegionCode', 'Partner']], 
    left_on='Partner', 
    right_on='RegionCode',
    how='inner',
    suffixes=('', '_beneficiary')
)

# Assign Official ISO codes to both sides
df_pref_bilateral['iso3_reporter'] = df_pref_bilateral['Reporter_ISO_N'].apply(to_official_iso)
df_pref_bilateral['iso3_exporter'] = df_pref_bilateral['Partner_beneficiary'].apply(to_official_iso)

# --- 5. Teti's Aggregation and Filtering ---
print("Applying Teti's 'Lowest Rate' and 'No-Increase' rules...")

# Rule 1: Multiple Agreements -> Lowest available rate
df_pref_bilateral = df_pref_bilateral.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

# Rule 2: Spike Filter (Treat increases over time as missing data)
df_pref_bilateral = df_pref_bilateral.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

def flag_spikes(group):
    # Calculate tariff difference; if > 0, it's a 'false' spike
    group['diff'] = group['prefAVE'].diff()
    group.loc[group['diff'] > 0, ['pref', 'prefAVE']] = np.nan
    return group

df_pref_bilateral = df_pref_bilateral.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode'], 
    group_keys=False
).apply(flag_spikes)

# Drop helper columns
df_pref_bilateral = df_pref_bilateral.drop(columns=['diff'])

print("\n--- Phase 1.8 Success ---")
print(f"Bilateral Pairs generated: {df_pref_bilateral['iso3_exporter'].nunique()} exporters found for Kazakhstan.")
display(df_pref_bilateral.head())

KeyError: 'ISO3'

In [42]:
import pandas as pd
import numpy as np
import os

# --- 1. BULLETPROOF MAPPING SETUP ---
print("Loading reference files...")
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin-1', header=0)
cl.columns = ['ISO3', 'CountryCode', 'CountryName']

pb = pd.read_csv('preference_beneficials.csv', sep=',', encoding='latin-1', header=0)
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

# --- 2. PREPARE THE LOOPS ---
mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not os.path.exists(file_path):
        print(f"  -> Missing file: {file_path}")
        return pd.DataFrame()
    
    df = pd.read_csv(file_path, encoding='latin-1')
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.zfill(6)
    return df

# Storage for the yearly dataframes
all_mfn_years = []
all_pref_years = []

# --- 3. PROCESS EVERY YEAR (2013-2023) ---
print("Processing yearly files...")
for year in range(2013, 2024):
    print(f"Processing Year {year}...")
    
    # Construct exact paths using your provided structure
    mfn_path = f"kazakhstan/mfn/MFN_KAZ_{year}.CSV"
    mfn_ave_path = f"kazakhstan/mfn ave/AVEMFN_KAZ_{year}.CSV"
    pref_path = f"kazakhstan/pref/Pref_KAZ_{year}.CSV"
    pref_ave_path = f"kazakhstan/pref ave/AVEPref_KAZ_{year}.CSV"
    
    # Load and clean
    df_mfn = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    df_mfn_ave = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    df_pref = clean_tariff_file(pref_path, 'pref', pref_drop)
    df_pref_ave = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    # Merge MFN for this year
    if not df_mfn.empty and not df_mfn_ave.empty:
        df_mfn_merged = pd.merge(df_mfn, df_mfn_ave, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer')
        all_mfn_years.append(df_mfn_merged)
        
    # Merge and Disaggregate PREF for this year
    if not df_pref.empty and not df_pref_ave.empty:
        df_pref_merged = pd.merge(df_pref, df_pref_ave, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
        
        # Explode to bilateral pairs using the pre-mapped beneficiaries list
        df_pref_bilateral = pd.merge(
            df_pref_merged, 
            pb[['RegionCode', 'iso3_exporter']], 
            left_on='Partner', 
            right_on='RegionCode', 
            how='inner'
        )
        all_pref_years.append(df_pref_bilateral)

# --- 4. CONCATENATE ALL YEARS INTO MASTER PANELS ---
print("\nConcatenating 2013-2023 panels...")
master_mfn = pd.concat(all_mfn_years, ignore_index=True)
master_pref = pd.concat(all_pref_years, ignore_index=True)

# Map Reporter ISOs
master_mfn['iso3_reporter'] = master_mfn['Reporter_ISO_N'].apply(to_official_iso)
master_pref['iso3_reporter'] = master_pref['Reporter_ISO_N'].apply(to_official_iso)

# --- 5. APPLY TETI TIME-SERIES RULES ---
print("Applying Teti (2024) Appendix F.2 rules across the panel...")

# Rule 1: Min Rate for overlapping agreements in the same year
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

# Rule 2: Preferential Spike Filter (Time-Series Check)
# Sort chronologically so .diff() checks the change from year to year
master_pref = master_pref.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

def flag_spikes(group):
    # If the preferential rate goes UP from one year to the next, it's an error. Mark as NaN.
    group['diff'] = group['prefAVE'].diff()
    group.loc[group['diff'] > 0, ['pref', 'prefAVE']] = np.nan
    return group

master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode'], 
    group_keys=False
).apply(flag_spikes)

master_pref = master_pref.drop(columns=['diff'], errors='ignore')

# Save the final Master Panels!
master_mfn.to_csv('KAZ_MFN_Master_2013_2023.csv', index=False)
master_pref.to_csv('KAZ_PREF_Master_2013_2023.csv', index=False)

print("\n--- PHASE 1 COMPLETE! ---")
print(f"Master MFN Rows: {len(master_mfn)}")
print(f"Master PREF Rows: {len(master_pref)}")

Loading reference files...
Processing yearly files...
Processing Year 2013...
Processing Year 2014...
Processing Year 2015...
Processing Year 2016...
Processing Year 2017...
Processing Year 2018...
Processing Year 2019...
Processing Year 2020...
Processing Year 2021...
Processing Year 2022...
Processing Year 2023...

Concatenating 2013-2023 panels...
Applying Teti (2024) Appendix F.2 rules across the panel...

/var/folders/n7/sybtfhvs5nb2h6lmw94vfc3c0000gn/T/ipykernel_56645/1071881610.py:121: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ).apply(flag_spikes)

--- PHASE 1 COMPLETE! ---
Master MFN Rows: 58986
Master PREF Rows: 2355210

In [43]:
import pandas as pd

# 1. Load your newly created Master Panel
df_pref = pd.read_csv('KAZ_PREF_Master_2013_2023.csv')

# 2. Check for missing (NaN) ISO3 codes
missing_iso = df_pref['iso3_exporter'].isna().sum()
print(f"1. Rows with missing Exporter ISO3: {missing_iso}")

# 3. Check for Suspicious/Aggregate Codes
unique_exporters = df_pref['iso3_exporter'].dropna().unique()

# Official ISO3 codes are exactly 3 alphabetical letters (A-Z)
suspicious_codes = [code for code in unique_exporters if len(str(code)) != 3 or not str(code).isalpha()]
print(f"2. Suspicious/Aggregate codes remaining: {suspicious_codes}")

# 4. View Total Unique Countries
print(f"3. Total unique partner countries found: {len(unique_exporters)}")

# 5. Print a sample of the codes to visually confirm
print(f"\nSample of first 20 valid ISO3 codes:\n{sorted(unique_exporters)[:20]}")

1. Rows with missing Exporter ISO3: 0
2. Suspicious/Aggregate codes remaining: []
3. Total unique partner countries found: 188

Sample of first 20 valid ISO3 codes:
['ABW', 'AFG', 'AGO', 'AIA', 'ALB', 'ARE', 'ARG', 'ARM', 'ASM', 'ATF', 'ATG', 'AZE', 'BDI', 'BEN', 'BFA', 'BGD', 'BHR', 'BHS', 'BIH', 'BLR']

In [44]:
# 1. Save as standard CSV files
master_mfn.to_csv('KAZ_MFN_Master_2013_2023.csv', index=False)
master_pref.to_csv('KAZ_PREF_Master_2013_2023.csv', index=False)
print("Saved as CSV files!")

# 2. OPTIONAL: Save as Stata (.dta) files for your regressions later
# (Requires the 'pandas' library to be up to date)
try:
    master_mfn.to_stata('KAZ_MFN_Master_2013_2023.dta', write_index=False)
    master_pref.to_stata('KAZ_PREF_Master_2013_2023.dta', write_index=False)
    print("Saved as Stata .dta files!")
except Exception as e:
    print(f"Could not save as Stata files. Error: {e}")

Saved as CSV files!
Saved as Stata .dta files!

In [52]:
import pandas as pd
import numpy as np

print("Loading Master Data...")
# 1. Load the Master files you just created
master_mfn = pd.read_csv('KAZ_MFN_Master_2013_2023.csv')
master_pref = pd.read_csv('KAZ_PREF_Master_2013_2023.csv')

# Ensure ProductCodes are 6-digit strings
master_mfn['ProductCode'] = master_mfn['ProductCode'].astype(str).str.zfill(6)
master_pref['ProductCode'] = master_pref['ProductCode'].astype(str).str.zfill(6)

# --- STEP 1: DEFINE THE UNIVERSE (THE SKELETON DIMENSIONS) ---
print("Building the Skeleton Matrices...")
years = list(range(2013, 2024))
reporter = 'KAZ'

# Get every unique product KAZ has ever imported across the whole decade
all_products = pd.concat([master_mfn['ProductCode'], master_pref['ProductCode']]).dropna().unique()

# Get every unique preferential partner KAZ has
pref_exporters = master_pref['iso3_exporter'].dropna().unique()

# --- STEP 2: CREATE THE SKELETONS ---
# MFN Skeleton: KAZ x Every Product x Every Year
mfn_idx = pd.MultiIndex.from_product(
    [[reporter], years, all_products], 
    names=['iso3_reporter', 'Year', 'ProductCode']
)
mfn_skeleton = pd.DataFrame(index=mfn_idx).reset_index()

# PREF Skeleton: KAZ x Every Exporter x Every Product x Every Year
pref_idx = pd.MultiIndex.from_product(
    [[reporter], pref_exporters, all_products, years], 
    names=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
)
pref_skeleton = pd.DataFrame(index=pref_idx).reset_index()

# --- STEP 3: MERGE DATA TO EXPOSE MISSING YEARS ---
print("Merging reported data onto skeletons to expose missing gaps...")
mfn_full = pd.merge(mfn_skeleton, master_mfn, on=['iso3_reporter', 'Year', 'ProductCode'], how='left')
pref_full = pd.merge(pref_skeleton, master_pref, on=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'], how='left')

# --- STEP 4: TETI INTERPOLATION (LOCF & NOCB) ---
print("Applying Teti (2024) chronological interpolation...")

# MFN Interpolation
mfn_full = mfn_full.sort_values(['iso3_reporter', 'ProductCode', 'Year'])
mfn_full[['mfn', 'mfnAVE']] = mfn_full.groupby(['iso3_reporter', 'ProductCode'])[['mfn', 'mfnAVE']].ffill().bfill()

# PREF Interpolation
pref_full = pref_full.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_full[['pref', 'prefAVE']] = pref_full.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])[['pref', 'prefAVE']].ffill().bfill()

# --- STEP 5: MERGE MFN AND PREF TOGETHER ---
print("Combining MFN and Preferential panels...")
final_panel = pd.merge(
    pref_full, 
    mfn_full[['iso3_reporter', 'Year', 'ProductCode', 'mfn', 'mfnAVE']], 
    on=['iso3_reporter', 'Year', 'ProductCode'], 
    how='left'
)

# --- STEP 6: APPLY THE CEILING RULE (CREATE 'Applied_Tariff') ---
print("Applying the Ceiling Rule to determine final Applied Tariffs...")

# 1. Start with the Preferential Rate
final_panel['Applied_Tariff'] = final_panel['pref']
final_panel['Applied_Tariff_AVE'] = final_panel['prefAVE']

# 2. If Preferential Rate is missing, default to the MFN rate
final_panel['Applied_Tariff'] = final_panel['Applied_Tariff'].fillna(final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = final_panel['Applied_Tariff_AVE'].fillna(final_panel['mfnAVE'])

# 3. The Ceiling Rule: The applied rate can NEVER be higher than the MFN rate
# We use np.fmin here because it safely handles NaNs if one column happens to be missing
final_panel['Applied_Tariff'] = np.fmin(final_panel['Applied_Tariff'], final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = np.fmin(final_panel['Applied_Tariff_AVE'], final_panel['mfnAVE'])

# --- 7. FINAL CLEANUP AND SAVE ---
print("Running final cleanup...")
# Drop rows where we have absolutely no tariff data at all (neither MFN nor PREF)
final_panel = final_panel.dropna(subset=['Applied_Tariff', 'Applied_Tariff_AVE'], how='all')

final_panel.to_csv('KAZ_Final_Applied_Tariffs_2013_2023.csv', index=False)

print("\n--- PHASE 2 COMPLETE! ---")

Loading Master Data...
Building the Skeleton Matrices...
Merging reported data onto skeletons to expose missing gaps...
Applying Teti (2024) chronological interpolation...
Combining MFN and Preferential panels...
Applying the Ceiling Rule to determine final Applied Tariffs...
Running final cleanup...

--- PHASE 2 COMPLETE! ---

In [53]:
final_panel

,iso3_reporter,iso3_exporter,ProductCode,Year,pref,prefAVE,mfn,mfnAVE,Applied_Tariff,Applied_Tariff_AVE
0,KAZ,ABW,010121,2013,11.25,17.81,0.0,0.0,0.0,0.0
1,KAZ,ABW,010121,2014,11.25,17.81,0.0,0.0,0.0,0.0
2,KAZ,ABW,010121,2015,11.25,17.81,0.0,0.0,0.0,0.0
3,KAZ,ABW,010121,2016,11.25,17.81,0.0,0.0,0.0,0.0
4,KAZ,ABW,010121,2017,11.25,17.81,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
12075047,KAZ,ZWE,970690,2019,NaN,NaN,0.0,0.0,0.0,0.0
12075048,KAZ,ZWE,970690,2020,NaN,NaN,0.0,0.0,0.0,0.0
12075049,KAZ,ZWE,970690,2021,NaN,NaN,0.0,0.0,0.0,0.0
12075050,KAZ,ZWE,970690,2022,NaN,NaN,0.0,0.0,0.0,0.0
12075051,KAZ,ZWE,970690,2023,NaN,NaN,0.0,0.0,0.0,0.0

In [59]:
import pandas as pd
import os

def find_file(target_name):
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f.lower() == target_name.lower():
                return os.path.join(root, f)
    return None

# Find one year of China data
mfn_file = find_file("MFN_CHN_2013.CSV")
pref_file = find_file("PREF_CHN_2013.CSV")

print("--- DIAGNOSTIC: STEP 1 ---")

if mfn_file:
    print(f"Found MFN at: {mfn_file}")
    df_mfn = pd.read_csv(mfn_file, encoding='latin-1', nrows=5)
    print("MFN Exact Columns:")
    print([repr(c) for c in df_mfn.columns])  # repr() shows hidden spaces
else:
    print("MFN_CHN_2013.CSV not found!")

if pref_file:
    print(f"\nFound PREF at: {pref_file}")
    df_pref = pd.read_csv(pref_file, encoding='latin-1', nrows=5)
    print("PREF Exact Columns:")
    print([repr(c) for c in df_pref.columns])
else:
    print("\nPREF_CHN_2013.CSV not found!")

--- DIAGNOSTIC: STEP 1 ---
Found MFN at: ./china mfn/MFN_CHN_2013.CSV
MFN Exact Columns:
["'NomenCode'", "'Reporter_ISO_N'", "'Year'", "'ProductCode'", "'Sum_Of_Rates'", "'Min_Rate'", "'Max_Rate'", "'SimpleAverage'", "'Nbr_NA_Lines'", "'Nbr_Free_Lines'", "'Nbr_AVE_Lines'", "'Nbr_Dutiable_Lines'", "'TotalNoOfValidLines'", "'TotalNoOfLines'"]

Found PREF at: ./china /china pref/PREF_CHN_2013.CSV
PREF Exact Columns:
["'NomenCode'", "'Reporter_ISO_N'", "'Year'", "'ProductCode'", "'Partner'", "'ExcludedFrom'", "'Sum_Of_Rates'", "'Min_Rate'", "'Max_Rate'", "'SimpleAverage'", "'TotalNoOfLines'", "'Nbr_Pref_Lines'", "'Nbr_MFN_Lines'", "'Nbr_NA_Lines'"]

In [62]:
import pandas as pd
import numpy as np
import os

print("--- STEP 1: INITIALIZING REFERENCE MAPS ---")

# 1. Load Country List and clean headers
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin-1')
# Forcefully strip invisible characters, spaces, and quotes from headers
cl.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in cl.columns]
# Rename just to be 100% safe
cl.columns = ['ISO3', 'CountryCode', 'CountryName'] 

# 2. Load Beneficiaries List and clean headers
pb = pd.read_csv('preference_beneficials.csv', sep=',', encoding='latin-1')
pb.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in pb.columns]
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

# 3. Create the Teti (2024) ISO Correction Dictionary
iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

# 4. Map CountryCode to ISO3
cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

# 5. Pre-map the beneficiaries list to Official ISO3
pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

print("Success! Reference maps loaded.")
print(f"Total mapped beneficiaries: {pb['iso3_exporter'].notna().sum()}")
print("-------------------------------------------")

--- STEP 1: INITIALIZING REFERENCE MAPS ---
Success! Reference maps loaded.
Total mapped beneficiaries: 27731
-------------------------------------------

In [63]:
print("--- STEP 2: LOADING AND CLEANING CHINA DATA ---")

mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not os.path.exists(file_path):
        print(f"  [!] Missing file: {file_path}")
        return pd.DataFrame()
    
    df = pd.read_csv(file_path, encoding='latin-1')
    
    # BRUTE FORCE CLEANING: Strip spaces, double quotes, and single quotes from column names
    df.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in df.columns]
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        # Also clean the actual ProductCode values inside the data, just in case they have quotes too!
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.replace('"', '').str.strip().str.zfill(6)
        
    return df

all_mfn_years = []
all_pref_years = []

for year in range(2013, 2024):
    print(f" -> Processing {year}...")
    
    # The paths exactly as you specified
    mfn_path = f"china mfn/MFN_CHN_{year}.CSV"
    mfn_ave_path = f"china mfn ave/AVEMFN_CHN_{year}.CSV"
    pref_path = f"china /china pref/PREF_CHN_{year}.CSV"
    pref_ave_path = f"china /china pref ave/AVEPREF_CHN_{year}.CSV"
    
    # Load and clean
    df_mfn = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    df_mfn_ave = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    df_pref = clean_tariff_file(pref_path, 'pref', pref_drop)
    df_pref_ave = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    # Merge MFN
    if not df_mfn.empty and not df_mfn_ave.empty:
        df_mfn_merged = pd.merge(df_mfn, df_mfn_ave, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer')
        all_mfn_years.append(df_mfn_merged)
        
    # Merge and Disaggregate PREF
    if not df_pref.empty and not df_pref_ave.empty:
        df_pref_merged = pd.merge(df_pref, df_pref_ave, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
        df_pref_bilateral = pd.merge(
            df_pref_merged, pb[['RegionCode', 'iso3_exporter']], 
            left_on='Partner', right_on='RegionCode', how='inner'
        )
        all_pref_years.append(df_pref_bilateral)

# Concatenate all years together
master_mfn = pd.concat(all_mfn_years, ignore_index=True)
master_pref = pd.concat(all_pref_years, ignore_index=True)

master_mfn['iso3_reporter'] = 'CHN'
master_pref['iso3_reporter'] = 'CHN'

print("\n--- STEP 2 SUCCESS! ---")
print("MFN Panel Columns:", master_mfn.columns.tolist())
print("PREF Panel Columns:", master_pref.columns.tolist())
print(f"Total MFN Rows: {len(master_mfn)}")
print(f"Total PREF Rows: {len(master_pref)}")

--- STEP 2: LOADING AND CLEANING CHINA DATA ---
 -> Processing 2013...
 -> Processing 2014...
 -> Processing 2015...
 -> Processing 2016...
 -> Processing 2017...
 -> Processing 2018...

/var/folders/n7/sybtfhvs5nb2h6lmw94vfc3c0000gn/T/ipykernel_56645/2579083174.py:14: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin-1')

 -> Processing 2019...
 -> Processing 2020...
 -> Processing 2021...
 -> Processing 2022...
 -> Processing 2023...

--- STEP 2 SUCCESS! ---
MFN Panel Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE', 'EstCode', 'iso3_reporter']
PREF Panel Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner', 'pref', 'prefAVE', 'RegionCode', 'iso3_exporter', 'iso3_reporter']
Total MFN Rows: 58987
Total PREF Rows: 2659223

In [67]:
import os
import pandas as pd

print("--- STEP 2: AUTO-DISCOVER AND CLEAN CHINA DATA ---")

def find_file(target_name):
    """Automatically searches all folders and subfolders for the exact file."""
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f.lower() == target_name.lower():
                return os.path.join(root, f)
    return None

mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not file_path:
        return pd.DataFrame()
    
    df = pd.read_csv(file_path, encoding='latin-1')
    
    # BRUTE FORCE CLEANING: Strip spaces, double quotes, and single quotes from column names
    df.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in df.columns]
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace("'", "").str.replace('"', '').str.strip().str.zfill(6)
        
    return df

all_mfn_years = []
all_pref_years = []

for year in range(2013, 2024):
    print(f" -> Searching for {year} files...")
    
    # AUTO-FIND THE FILES
    mfn_path = find_file(f"MFN_CHN_{year}.CSV")
    mfn_ave_path = find_file(f"AVEMFN_CHN_{year}.CSV")
    pref_path = find_file(f"PREF_CHN_{year}.CSV")
    pref_ave_path = find_file(f"AVEPREF_CHN_{year}.CSV")
    
    # Load and clean
    df_mfn = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    df_mfn_ave = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    df_pref = clean_tariff_file(pref_path, 'pref', pref_drop)
    df_pref_ave = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    # Merge MFN
    if not df_mfn.empty and not df_mfn_ave.empty:
        df_mfn_merged = pd.merge(df_mfn, df_mfn_ave, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer')
        all_mfn_years.append(df_mfn_merged)

--- STEP 2: AUTO-DISCOVER AND CLEAN CHINA DATA ---
 -> Searching for 2013 files...
 -> Searching for 2014 files...
 -> Searching for 2015 files...
 -> Searching for 2016 files...
 -> Searching for 2017 files...

/var/folders/n7/sybtfhvs5nb2h6lmw94vfc3c0000gn/T/ipykernel_56645/949139322.py:24: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding='latin-1')

 -> Searching for 2018 files...
 -> Searching for 2019 files...
 -> Searching for 2020 files...
 -> Searching for 2021 files...
 -> Searching for 2022 files...
 -> Searching for 2023 files...

In [68]:
import os
import pandas as pd

print("--- DIAGNOSTIC: CHECKING CHINA FILES ---")

def find_file(target_name):
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f.lower() == target_name.lower():
                return os.path.join(root, f)
    return None

for year in range(2013, 2015): # Just checking the first two years to keep it brief
    print(f"\nSearching for {year}:")
    
    mfn_path = find_file(f"MFN_CHN_{year}.CSV")
    mfn_ave_path = find_file(f"AVEMFN_CHN_{year}.CSV")
    pref_path = find_file(f"PREF_CHN_{year}.CSV")
    pref_ave_path = find_file(f"AVEPREF_CHN_{year}.CSV")
    
    print(f"  MFN File:      {'FOUND' if mfn_path else 'MISSING'} ({mfn_path})")
    print(f"  MFN AVE File:  {'FOUND' if mfn_ave_path else 'MISSING'} ({mfn_ave_path})")
    print(f"  PREF File:     {'FOUND' if pref_path else 'MISSING'} ({pref_path})")
    print(f"  PREF AVE File: {'FOUND' if pref_ave_path else 'MISSING'} ({pref_ave_path})")
    
    # If MFN 2013 is found, let's print its exact columns to be 100% sure
    if year == 2013 and mfn_path:
        df = pd.read_csv(mfn_path, encoding='latin-1', nrows=2, low_memory=False)
        cleaned_cols = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in df.columns]
        print(f"\n  [2013 MFN] Raw Columns: {df.columns.tolist()}")
        print(f"  [2013 MFN] Cleaned Columns: {cleaned_cols}")

print("\n----------------------------------------")

--- DIAGNOSTIC: CHECKING CHINA FILES ---

Searching for 2013:
  MFN File:      FOUND (./china mfn/MFN_CHN_2013.CSV)
  MFN AVE File:  FOUND (./china mfn ave/AVEMFN_CHN_2013.CSV)
  PREF File:     FOUND (./china /china pref/PREF_CHN_2013.CSV)
  PREF AVE File: FOUND (./china /china pref ave/AVEPREF_CHN_2013.CSV)

  [2013 MFN] Raw Columns: ['NomenCode', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'SimpleAverage', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines']
  [2013 MFN] Cleaned Columns: ['NomenCode', 'Reporter_ISO_N', 'Year', 'ProductCode', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'SimpleAverage', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines']

Searching for 2014:
  MFN File:      FOUND (./china mfn/MFN_CHN_2014.CSV)
  MFN AVE File:  FOUND (./china mfn ave/AVEMFN_CHN_2014.CSV)
  PREF File:     FOUND (./china /china pref/PREF_CHN_2014.CSV)
  PREF AVE File: FOUND (./china /china pref ave/AVEPREF_CHN_2014.CSV)

----------------------------------------

In [70]:
import os
import pandas as pd
import numpy as np

print("--- STARTING CHINA MASTER DATA CONSTRUCTION ---")

# --- STEP 1: REFERENCE MAPS ---
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin-1')
# FIX: Clean the headers and rename them properly so 'ISO3' exists!
cl.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in cl.columns]
cl.columns = ['ISO3', 'CountryCode', 'CountryName']

pb = pd.read_csv('preference_beneficials.csv', sep=',', encoding='latin-1')
# FIX: Clean the headers for preferences too
pb.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in pb.columns]
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

# --- STEP 2: LOAD AND MERGE TARIFFS ---
mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not os.path.exists(file_path):
        return pd.DataFrame()
    
    # low_memory=False prevents the DtypeWarning you saw in 2017
    df = pd.read_csv(file_path, encoding='latin-1', low_memory=False)
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        # Strip any accidental .0 decimals and ensure 6 digits
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace(".0", "", regex=False).str.zfill(6)
        
    return df

all_mfn = []
all_pref = []

for year in range(2013, 2024):
    print(f" -> Processing {year}...")
    
    # THE EXACT PATHS DISCOVERED BY THE DIAGNOSTIC
    mfn_path = f"china mfn/MFN_CHN_{year}.CSV"
    mfn_ave_path = f"china mfn ave/AVEMFN_CHN_{year}.CSV"
    pref_path = f"china /china pref/PREF_CHN_{year}.CSV"
    pref_ave_path = f"china /china pref ave/AVEPREF_CHN_{year}.CSV"
    
    m = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    ma = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    p = clean_tariff_file(pref_path, 'pref', pref_drop)
    pa = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    if not m.empty and not ma.empty:
        all_mfn.append(pd.merge(m, ma, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer'))
        
    if not p.empty and not pa.empty:
        pref_merge = pd.merge(p, pa, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
        pref_bilateral = pd.merge(pref_merge, pb[['RegionCode', 'iso3_exporter']], left_on='Partner', right_on='RegionCode', how='inner')
        all_pref.append(pref_bilateral)

print("Concatenating data (this might take a few seconds)...")
master_mfn = pd.concat(all_mfn, ignore_index=True)
master_pref = pd.concat(all_pref, ignore_index=True)

master_mfn['iso3_reporter'] = 'CHN'
master_pref['iso3_reporter'] = 'CHN'

print("\n--- STEP 1 & 2 SUCCESS ---")
print(f"MFN Rows: {len(master_mfn)}")
print(f"PREF Rows: {len(master_pref)}")
print(f"MFN Columns: {master_mfn.columns.tolist()}")

--- STARTING CHINA MASTER DATA CONSTRUCTION ---
 -> Processing 2013...
 -> Processing 2014...
 -> Processing 2015...
 -> Processing 2016...
 -> Processing 2017...
 -> Processing 2018...
 -> Processing 2019...
 -> Processing 2020...
 -> Processing 2021...
 -> Processing 2022...
 -> Processing 2023...
Concatenating data (this might take a few seconds)...

--- STEP 1 & 2 SUCCESS ---
MFN Rows: 58987
PREF Rows: 2659223
MFN Columns: ['Reporter_ISO_N', 'Year', 'ProductCode', 'mfn', 'mfnAVE', 'EstCode', 'iso3_reporter']

In [71]:
print("--- STEP 3: APPLYING TETI SPIKE FILTER ---")

# 1. Minimum available rate for overlapping agreements
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

# 2. Preferential Spike Filter (Time-Series Check)
# Sort chronologically so .diff() checks the change from year to year correctly
master_pref = master_pref.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

def flag_spikes(group):
    # If the preferential rate goes UP from one year to the next, mark as NaN
    group['diff'] = group['prefAVE'].diff()
    group.loc[group['diff'] > 0, ['pref', 'prefAVE']] = np.nan
    return group

# Apply the filter (include_groups=False silences the Pandas deprecation warning)
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode'], group_keys=False
).apply(flag_spikes, include_groups=False)

# Clean up the temporary 'diff' column
master_pref = master_pref.drop(columns=['diff'], errors='ignore')

print("Spike filter applied successfully!")
print(f"Total PREF Rows after filtering: {len(master_pref)}")
print("------------------------------------------")

--- STEP 3: APPLYING TETI SPIKE FILTER ---
Spike filter applied successfully!
Total PREF Rows after filtering: 2437190
------------------------------------------

In [74]:
import os
import pandas as pd
import numpy as np

print("--- STARTING ULTIMATE CHINA MASTER SCRIPT ---")

# ==========================================
# STEP 1: REFERENCE MAPS
# ==========================================
print("1. Loading reference maps...")
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin-1')
cl.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in cl.columns]
cl.columns = ['ISO3', 'CountryCode', 'CountryName']

pb = pd.read_csv('preference_beneficials.csv', sep=',', encoding='latin-1')
pb.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in pb.columns]
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

# ==========================================
# STEP 2: LOAD AND MERGE TARIFFS
# ==========================================
print("2. Loading and cleaning yearly data...")
mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not os.path.exists(file_path):
        return pd.DataFrame()
    
    df = pd.read_csv(file_path, encoding='latin-1', low_memory=False)
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace(".0", "", regex=False).str.zfill(6)
        
    return df

all_mfn, all_pref = [], []

for year in range(2013, 2024):
    mfn_path = f"china mfn/MFN_CHN_{year}.CSV"
    mfn_ave_path = f"china mfn ave/AVEMFN_CHN_{year}.CSV"
    pref_path = f"china /china pref/PREF_CHN_{year}.CSV"
    pref_ave_path = f"china /china pref ave/AVEPREF_CHN_{year}.CSV"
    
    m = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    ma = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    p = clean_tariff_file(pref_path, 'pref', pref_drop)
    pa = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    if not m.empty and not ma.empty:
        all_mfn.append(pd.merge(m, ma, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer'))
        
    if not p.empty and not pa.empty:
        pref_merge = pd.merge(p, pa, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
        pref_bilateral = pd.merge(pref_merge, pb[['RegionCode', 'iso3_exporter']], left_on='Partner', right_on='RegionCode', how='inner')
        all_pref.append(pref_bilateral)

master_mfn = pd.concat(all_mfn, ignore_index=True)
master_pref = pd.concat(all_pref, ignore_index=True)

master_mfn['iso3_reporter'] = 'CHN'
master_pref['iso3_reporter'] = 'CHN'

# ==========================================
# STEP 3: TETI SPIKE FILTER (VECTORIZED)
# ==========================================
print("3. Applying time-series spike filter...")
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

master_pref = master_pref.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

# Safe Vectorized calculation!
master_pref['diff'] = master_pref.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])['prefAVE'].diff()
master_pref.loc[master_pref['diff'] > 0, ['pref', 'prefAVE']] = np.nan
master_pref = master_pref.drop(columns=['diff'])

# ==========================================
# STEP 4: SKELETON MATRIX & INTERPOLATION
# ==========================================
print("4. Building Skeletons and Interpolating...")
years = list(range(2013, 2024))
all_products = pd.concat([master_mfn['ProductCode'], master_pref['ProductCode']]).dropna().unique()
pref_exporters = master_pref['iso3_exporter'].dropna().unique()

mfn_idx = pd.MultiIndex.from_product([['CHN'], years, all_products], names=['iso3_reporter', 'Year', 'ProductCode'])
mfn_skeleton = pd.DataFrame(index=mfn_idx).reset_index()

pref_idx = pd.MultiIndex.from_product([['CHN'], pref_exporters, all_products, years], names=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_skeleton = pd.DataFrame(index=pref_idx).reset_index()

mfn_full = pd.merge(mfn_skeleton, master_mfn, on=['iso3_reporter', 'Year', 'ProductCode'], how='left')
pref_full = pd.merge(pref_skeleton, master_pref, on=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'], how='left')

mfn_full = mfn_full.sort_values(['iso3_reporter', 'ProductCode', 'Year'])
mfn_full[['mfn', 'mfnAVE']] = mfn_full.groupby(['iso3_reporter', 'ProductCode'])[['mfn', 'mfnAVE']].ffill().bfill()

pref_full = pref_full.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_full[['pref', 'prefAVE']] = pref_full.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])[['pref', 'prefAVE']].ffill().bfill()

# ==========================================
# STEP 5: FINAL MERGE & CEILING RULE
# ==========================================
print("5. Applying Ceiling Rule and Exporting...")
final_panel = pd.merge(
    pref_full, 
    mfn_full[['iso3_reporter', 'Year', 'ProductCode', 'mfn', 'mfnAVE']], 
    on=['iso3_reporter', 'Year', 'ProductCode'], 
    how='left'
)

final_panel['Applied_Tariff'] = final_panel['pref'].fillna(final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = final_panel['prefAVE'].fillna(final_panel['mfnAVE'])

final_panel['Applied_Tariff'] = np.fmin(final_panel['Applied_Tariff'], final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = np.fmin(final_panel['Applied_Tariff_AVE'], final_panel['mfnAVE'])

final_panel = final_panel.dropna(subset=['Applied_Tariff', 'Applied_Tariff_AVE'], how='all')

try:
    final_panel.to_stata('CHN_Final_Applied_Tariffs_2013_2023.dta', write_index=False, version=118)
    print("\n--- DONE! CHINA DATASET IS COMPLETE! ---")
    print(f"File successfully saved: CHN_Final_Applied_Tariffs_2013_2023.dta")
except Exception as e:
    print(f"\nError saving to Stata: {e}")
    final_panel.to_csv('CHN_Final_Applied_Tariffs_2013_2023.csv', index=False)
    print("Saved as CSV instead due to Stata export error.")

--- STARTING ULTIMATE CHINA MASTER SCRIPT ---
1. Loading reference maps...
2. Loading and cleaning yearly data...
3. Applying time-series spike filter...
4. Building Skeletons and Interpolating...
5. Applying Ceiling Rule and Exporting...

--- DONE! CHINA DATASET IS COMPLETE! ---
File successfully saved: CHN_Final_Applied_Tariffs_2013_2023.dta

In [75]:
print("Exporting to CSV...")

# Save the final panel to a CSV file (index=False prevents adding a useless row-number column)
final_panel.to_csv('CHN_Final_Applied_Tariffs_2013_2023.csv', index=False)

print("\n--- DONE! CHINA DATASET IS COMPLETE! ---")
print(f"File successfully saved: CHN_Final_Applied_Tariffs_2013_2023.csv")
print(f"Final shape: {final_panel.shape}")

Exporting to CSV...

--- DONE! CHINA DATASET IS COMPLETE! ---
File successfully saved: CHN_Final_Applied_Tariffs_2013_2023.csv
Final shape: (3725909, 10)

In [2]:
import os
import pandas as pd
import numpy as np

print("--- STARTING ULTIMATE INDIA MASTER SCRIPT ---")

# ==========================================
# STEP 1: REFERENCE MAPS
# ==========================================
print("1. Loading reference maps...")
cl = pd.read_csv('country_list.csv', sep=';', encoding='latin-1')
cl.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in cl.columns]
cl.columns = ['ISO3', 'CountryCode', 'CountryName']

pb = pd.read_csv('preference_beneficials.csv', sep=',', encoding='latin-1')
pb.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in pb.columns]
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

# ==========================================
# STEP 2: LOAD AND MERGE TARIFFS
# ==========================================
print("2. Loading and cleaning yearly data for India...")
mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not os.path.exists(file_path):
        return pd.DataFrame() # Gracefully return empty dataframe if file is missing
    
    df = pd.read_csv(file_path, encoding='latin-1', low_memory=False)
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace(".0", "", regex=False).str.zfill(6)
        
    return df

all_mfn, all_pref = [], []

for year in range(2013, 2024):
    # Adjust these paths if your India folders are named slightly differently!
    mfn_path = f"india/mfn/MFN_IND_{year}.CSV"
    mfn_ave_path = f"india/mfn ave/AVEMFN_IND_{year}.CSV"
    pref_path = f"india/pref/PREF_IND_{year}.CSV"
    pref_ave_path = f"india/pref ave/AVEPREF_IND_{year}.CSV"
    
    m = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    ma = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    p = clean_tariff_file(pref_path, 'pref', pref_drop)
    pa = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    # Merge MFN (Handles missing MFN AVE files gracefully)
    if not m.empty:
        if ma.empty:
            all_mfn.append(m)
        else:
            all_mfn.append(pd.merge(m, ma, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer'))
            
    # Merge PREF (Handles missing PREF AVE files gracefully)
    if not p.empty:
        if pa.empty:
            pref_merge = p
        else:
            pref_merge = pd.merge(p, pa, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
            
        pref_bilateral = pd.merge(pref_merge, pb[['RegionCode', 'iso3_exporter']], left_on='Partner', right_on='RegionCode', how='inner')
        all_pref.append(pref_bilateral)

master_mfn = pd.concat(all_mfn, ignore_index=True) if all_mfn else pd.DataFrame()
master_pref = pd.concat(all_pref, ignore_index=True) if all_pref else pd.DataFrame()

if master_mfn.empty or master_pref.empty:
    raise ValueError("CRITICAL: Failed to load data. Please check your India folder paths.")

master_mfn['iso3_reporter'] = 'IND'
master_pref['iso3_reporter'] = 'IND'

print(f"Loaded {len(master_mfn)} raw MFN rows and {len(master_pref)} raw PREF rows.")

# ==========================================
# STEP 3: TETI SPIKE FILTER (VECTORIZED)
# ==========================================
print("3. Applying time-series spike filter...")
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

master_pref = master_pref.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

# Safe Vectorized calculation
if 'prefAVE' in master_pref.columns:
    master_pref['diff'] = master_pref.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])['prefAVE'].diff()
    master_pref.loc[master_pref['diff'] > 0, ['pref', 'prefAVE']] = np.nan
    master_pref = master_pref.drop(columns=['diff'])

# ==========================================
# STEP 4: SKELETON MATRIX & INTERPOLATION
# ==========================================
print("4. Building Skeletons and Interpolating (Applying ffill & bfill)...")
years = list(range(2013, 2024))
all_products = pd.concat([master_mfn['ProductCode'], master_pref['ProductCode']]).dropna().unique()
pref_exporters = master_pref['iso3_exporter'].dropna().unique()

mfn_idx = pd.MultiIndex.from_product([['IND'], years, all_products], names=['iso3_reporter', 'Year', 'ProductCode'])
mfn_skeleton = pd.DataFrame(index=mfn_idx).reset_index()

pref_idx = pd.MultiIndex.from_product([['IND'], pref_exporters, all_products, years], names=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_skeleton = pd.DataFrame(index=pref_idx).reset_index()

mfn_full = pd.merge(mfn_skeleton, master_mfn, on=['iso3_reporter', 'Year', 'ProductCode'], how='left')
pref_full = pd.merge(pref_skeleton, master_pref, on=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'], how='left')

# Forward Fill first, then Backward Fill to catch early gaps like 2013!
mfn_full = mfn_full.sort_values(['iso3_reporter', 'ProductCode', 'Year'])
mfn_full[['mfn', 'mfnAVE']] = mfn_full.groupby(['iso3_reporter', 'ProductCode'])[['mfn', 'mfnAVE']].ffill().bfill()

pref_full = pref_full.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_full[['pref', 'prefAVE']] = pref_full.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])[['pref', 'prefAVE']].ffill().bfill()

# ==========================================
# STEP 5: FINAL MERGE & CEILING RULE
# ==========================================
print("5. Applying Ceiling Rule and Exporting to CSV...")
final_panel = pd.merge(
    pref_full, 
    mfn_full[['iso3_reporter', 'Year', 'ProductCode', 'mfn', 'mfnAVE']], 
    on=['iso3_reporter', 'Year', 'ProductCode'], 
    how='left'
)

# Ensure AVE columns exist even if ALL AVE files were missing for some reason
if 'prefAVE' not in final_panel.columns: final_panel['prefAVE'] = np.nan
if 'mfnAVE' not in final_panel.columns: final_panel['mfnAVE'] = np.nan

# Create Fontagné-compliant Applied Tariffs
final_panel['Applied_Tariff'] = final_panel['pref'].fillna(final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = final_panel['prefAVE'].fillna(final_panel['mfnAVE'])

# Apply Teti's Ceiling Rule mathematically
final_panel['Applied_Tariff'] = np.fmin(final_panel['Applied_Tariff'], final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = np.fmin(final_panel['Applied_Tariff_AVE'], final_panel['mfnAVE'])

# Clean up empty rows
final_panel = final_panel.dropna(subset=['Applied_Tariff', 'Applied_Tariff_AVE'], how='all')

# EXPORT
final_panel.to_csv('IND_Final_Applied_Tariffs_2013_2023.csv', index=False)

print("\n--- DONE! INDIA DATASET IS COMPLETE! ---")
print(f"File successfully saved: IND_Final_Applied_Tariffs_2013_2023.csv")
print(f"Final shape: {final_panel.shape}")

--- STARTING ULTIMATE INDIA MASTER SCRIPT ---
1. Loading reference maps...
2. Loading and cleaning yearly data for India...
Loaded 64200 raw MFN rows and 2837660 raw PREF rows.
3. Applying time-series spike filter...
4. Building Skeletons and Interpolating (Applying ffill & bfill)...
5. Applying Ceiling Rule and Exporting to CSV...

--- DONE! INDIA DATASET IS COMPLETE! ---
File successfully saved: IND_Final_Applied_Tariffs_2013_2023.csv
Final shape: (6744679, 10)

In [4]:
# ==========================================
# STEP 5: FINAL MERGE & CEILING RULE
# ==========================================
print("5. Applying Ceiling Rule and Exporting to Stata (.dta)...")
final_panel = pd.merge(
    pref_full, 
    mfn_full[['iso3_reporter', 'Year', 'ProductCode', 'mfn', 'mfnAVE']], 
    on=['iso3_reporter', 'Year', 'ProductCode'], 
    how='left'
)

# Ensure AVE columns exist even if ALL AVE files were missing for some reason
if 'prefAVE' not in final_panel.columns: final_panel['prefAVE'] = np.nan
if 'mfnAVE' not in final_panel.columns: final_panel['mfnAVE'] = np.nan

# Create Fontagné-compliant Applied Tariffs
final_panel['Applied_Tariff'] = final_panel['pref'].fillna(final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = final_panel['prefAVE'].fillna(final_panel['mfnAVE'])

# Apply Teti's Ceiling Rule mathematically
final_panel['Applied_Tariff'] = np.fmin(final_panel['Applied_Tariff'], final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = np.fmin(final_panel['Applied_Tariff_AVE'], final_panel['mfnAVE'])

# Clean up empty rows
final_panel = final_panel.dropna(subset=['Applied_Tariff', 'Applied_Tariff_AVE'], how='all')

# EXPORT TO STATA (.dta)
print("Exporting to Stata (.dta)...")
try:
    final_panel.to_stata('IND_Final_Applied_Tariffs_2013_2023.dta', write_index=False, version=118)
    print("\n--- DONE! INDIA DATASET IS COMPLETE! ---")
    print(f"File successfully saved: IND_Final_Applied_Tariffs_2013_2023.dta")
    print(f"Final shape: {final_panel.shape}")
except Exception as e:
    print(f"\nError saving to Stata: {e}")
    # Fallback to CSV just in case Stata throws a fit over column types
    final_panel.to_csv('IND_Final_Applied_Tariffs_2013_2023.csv', index=False)
    print("Saved as CSV instead due to Stata export error.")

5. Applying Ceiling Rule and Exporting to Stata (.dta)...
Exporting to Stata (.dta)...

--- DONE! INDIA DATASET IS COMPLETE! ---
File successfully saved: IND_Final_Applied_Tariffs_2013_2023.dta
Final shape: (6744679, 10)

In [5]:
import os
import pandas as pd
import numpy as np

print("--- STARTING ULTIMATE PAKISTAN MASTER SCRIPT ---")

# ==========================================
# 0. AUTO-DISCOVERY FUNCTION
# ==========================================
def find_file(target_name):
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f.lower() == target_name.lower():
                return os.path.join(root, f)
    return None

# ==========================================
# STEP 1: REFERENCE MAPS
# ==========================================
print("1. Loading reference maps...")
cl_path, pb_path = find_file('country_list.csv'), find_file('preference_beneficials.csv')
cl = pd.read_csv(cl_path, sep=';', encoding='latin-1')
cl.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in cl.columns]
cl.columns = ['ISO3', 'CountryCode', 'CountryName']

pb = pd.read_csv(pb_path, sep=',', encoding='latin-1')
pb.columns = [str(c).strip().replace('\ufeff', '').replace('"', '').replace("'", "") for c in pb.columns]
pb.columns = ['RegionCode', 'RegionName', 'Partner', 'PartnerName']

iso_correction = {
    'ROM': 'ROU', 'ZAR': 'COD', 'TMP': 'TLS', 'SUD': 'SDN',
    'SAM': 'WSM', 'SER': 'SRB', 'MNE': 'MNE', 'ANT': 'CUW',
    'WLF': 'WLF', 'SVK': 'SVK'
}

cl['CountryCode'] = pd.to_numeric(cl['CountryCode'], errors='coerce')
iso_dict = cl.set_index('CountryCode')['ISO3'].to_dict()

def to_official_iso(numeric_code):
    try:
        wits_iso = iso_dict.get(int(float(numeric_code)))
        return iso_correction.get(wits_iso, wits_iso)
    except:
        return np.nan

pb['iso3_exporter'] = pb['Partner'].apply(to_official_iso)

# ==========================================
# STEP 2: LOAD AND MERGE TARIFFS
# ==========================================
print("2. Loading and cleaning yearly data for Pakistan...")
mfn_drop = ['Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'Nbr_NA_Lines', 'Nbr_Free_Lines', 
            'Nbr_AVE_Lines', 'Nbr_Dutiable_Lines', 'TotalNoOfValidLines', 'TotalNoOfLines', 'NomenCode']

pref_drop = ['ExcludedFrom', 'Sum_Of_Rates', 'Min_Rate', 'Max_Rate', 'TotalNoOfLines', 
             'Nbr_Pref_Lines', 'Nbr_MFN_Lines', 'Nbr_NA_Lines', 'NomenCode', 'EstCode']

def clean_tariff_file(file_path, rate_name, drop_list):
    if not file_path or not os.path.exists(file_path):
        return pd.DataFrame() # Gracefully handle Pakistan's missing 2013/2017 files
    
    df = pd.read_csv(file_path, encoding='latin-1', low_memory=False)
    
    if 'SimpleAverage' in df.columns:
        df = df.rename(columns={'SimpleAverage': rate_name})
        
    df = df.drop(columns=[c for c in drop_list if c in df.columns], errors='ignore')
    
    if 'ProductCode' in df.columns:
        df['ProductCode'] = df['ProductCode'].astype(str).str.replace(".0", "", regex=False).str.zfill(6)
        
    return df

all_mfn, all_pref = [], []

for year in range(2013, 2024):
    print(f" -> Searching for {year} files...")
    # Using the likely folder structure, but auto-discovery will help if it varies
    mfn_path = find_file(f"MFN_PAK_{year}.CSV")
    mfn_ave_path = find_file(f"AVEMFN_PAK_{year}.CSV")
    pref_path = find_file(f"PREF_PAK_{year}.CSV")
    pref_ave_path = find_file(f"AVEPREF_PAK_{year}.CSV")
    
    m = clean_tariff_file(mfn_path, 'mfn', mfn_drop)
    ma = clean_tariff_file(mfn_ave_path, 'mfnAVE', mfn_drop)
    p = clean_tariff_file(pref_path, 'pref', pref_drop)
    pa = clean_tariff_file(pref_ave_path, 'prefAVE', pref_drop)
    
    if not m.empty:
        if ma.empty:
            all_mfn.append(m)
        else:
            all_mfn.append(pd.merge(m, ma, on=['Reporter_ISO_N', 'Year', 'ProductCode'], how='outer'))
            
    if not p.empty:
        if pa.empty:
            pref_merge = p
        else:
            pref_merge = pd.merge(p, pa, on=['Reporter_ISO_N', 'Year', 'ProductCode', 'Partner'], how='outer')
            
        pref_bilateral = pd.merge(pref_merge, pb[['RegionCode', 'iso3_exporter']], left_on='Partner', right_on='RegionCode', how='inner')
        all_pref.append(pref_bilateral)

master_mfn = pd.concat(all_mfn, ignore_index=True) if all_mfn else pd.DataFrame()
master_pref = pd.concat(all_pref, ignore_index=True) if all_pref else pd.DataFrame()

if master_mfn.empty or master_pref.empty:
    raise ValueError("CRITICAL: Failed to load data. Please check your Pakistan folder and file names.")

master_mfn['iso3_reporter'] = 'PAK'
master_pref['iso3_reporter'] = 'PAK'

print(f"Loaded {len(master_mfn)} raw MFN rows and {len(master_pref)} raw PREF rows.")

# ==========================================
# STEP 3: TETI SPIKE FILTER (VECTORIZED)
# ==========================================
print("3. Applying time-series spike filter...")
master_pref = master_pref.groupby(
    ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year']
).agg({'pref': 'min', 'prefAVE': 'min'}).reset_index()

master_pref = master_pref.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])

if 'prefAVE' in master_pref.columns:
    master_pref['diff'] = master_pref.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])['prefAVE'].diff()
    master_pref.loc[master_pref['diff'] > 0, ['pref', 'prefAVE']] = np.nan
    master_pref = master_pref.drop(columns=['diff'])

# ==========================================
# STEP 4: SKELETON MATRIX & INTERPOLATION
# ==========================================

print("4. Building Skeletons and Interpolating (Applying ffill & bfill)...")
years = list(range(2013, 2024))
all_products = pd.concat([master_mfn['ProductCode'], master_pref['ProductCode']]).dropna().unique()
pref_exporters = master_pref['iso3_exporter'].dropna().unique()

mfn_idx = pd.MultiIndex.from_product([['PAK'], years, all_products], names=['iso3_reporter', 'Year', 'ProductCode'])
mfn_skeleton = pd.DataFrame(index=mfn_idx).reset_index()

pref_idx = pd.MultiIndex.from_product([['PAK'], pref_exporters, all_products, years], names=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_skeleton = pd.DataFrame(index=pref_idx).reset_index()

mfn_full = pd.merge(mfn_skeleton, master_mfn, on=['iso3_reporter', 'Year', 'ProductCode'], how='left')
pref_full = pd.merge(pref_skeleton, master_pref, on=['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'], how='left')

mfn_full = mfn_full.sort_values(['iso3_reporter', 'ProductCode', 'Year'])
mfn_full[['mfn', 'mfnAVE']] = mfn_full.groupby(['iso3_reporter', 'ProductCode'])[['mfn', 'mfnAVE']].ffill().bfill()

pref_full = pref_full.sort_values(['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year'])
pref_full[['pref', 'prefAVE']] = pref_full.groupby(['iso3_reporter', 'iso3_exporter', 'ProductCode'])[['pref', 'prefAVE']].ffill().bfill()

# ==========================================
# STEP 5: FINAL MERGE & CEILING RULE
# ==========================================
print("5. Applying Ceiling Rule and Exporting to Stata (.dta)...")
final_panel = pd.merge(
    pref_full, 
    mfn_full[['iso3_reporter', 'Year', 'ProductCode', 'mfn', 'mfnAVE']], 
    on=['iso3_reporter', 'Year', 'ProductCode'], 
    how='left'
)

if 'prefAVE' not in final_panel.columns: final_panel['prefAVE'] = np.nan
if 'mfnAVE' not in final_panel.columns: final_panel['mfnAVE'] = np.nan

final_panel['Applied_Tariff'] = final_panel['pref'].fillna(final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = final_panel['prefAVE'].fillna(final_panel['mfnAVE'])

final_panel['Applied_Tariff'] = np.fmin(final_panel['Applied_Tariff'], final_panel['mfn'])
final_panel['Applied_Tariff_AVE'] = np.fmin(final_panel['Applied_Tariff_AVE'], final_panel['mfnAVE'])

final_panel = final_panel.dropna(subset=['Applied_Tariff', 'Applied_Tariff_AVE'], how='all')

print("Exporting to Stata (.dta)...")
try:
    final_panel.to_stata('PAK_Final_Applied_Tariffs_2013_2023.dta', write_index=False, version=118)
    print("\n--- DONE! PAKISTAN DATASET IS COMPLETE! ---")
    print(f"File successfully saved: PAK_Final_Applied_Tariffs_2013_2023.dta")
    print(f"Final shape: {final_panel.shape}")
except Exception as e:
    print(f"\nError saving to Stata: {e}")
    final_panel.to_csv('PAK_Final_Applied_Tariffs_2013_2023.csv', index=False)
    print("Saved as CSV instead due to Stata export error.")

--- STARTING ULTIMATE PAKISTAN MASTER SCRIPT ---
1. Loading reference maps...
2. Loading and cleaning yearly data for Pakistan...
 -> Searching for 2013 files...
 -> Searching for 2014 files...
 -> Searching for 2015 files...
 -> Searching for 2016 files...
 -> Searching for 2017 files...
 -> Searching for 2018 files...
 -> Searching for 2019 files...
 -> Searching for 2020 files...
 -> Searching for 2021 files...
 -> Searching for 2022 files...
 -> Searching for 2023 files...
Loaded 58988 raw MFN rows and 148943 raw PREF rows.
3. Applying time-series spike filter...
4. Building Skeletons and Interpolating (Applying ffill & bfill)...
5. Applying Ceiling Rule and Exporting to Stata (.dta)...
Exporting to Stata (.dta)...

--- DONE! PAKISTAN DATASET IS COMPLETE! ---
File successfully saved: PAK_Final_Applied_Tariffs_2013_2023.dta
Final shape: (513986, 10)

In [7]:
final_panel.to_csv('PAK_Final_Applied_Tariffs_2013_2023.csv', index=False)

In [9]:
import pandas as pd
import os

print("--- STARTING MASTER CSV PANEL MERGE ---")

# 1. Define the exact CSV files to merge
target_files = [
    'CHN_Final_Applied_Tariffs_2013_2023.csv',
    'IND_Final_Applied_Tariffs_2013_2023.csv',
    'PAK_Final_Applied_Tariffs_2013_2023.csv',
    'KAZ_Final_Applied_Tariffs_2013_2023.csv' 
]

all_panels = []

# 2. Load and stack the data
for file in target_files:
    if os.path.exists(file):
        print(f"Loading {file}...")
        # low_memory=False prevents Pandas from guessing column types too early
        df = pd.read_csv(file, low_memory=False)
        all_panels.append(df)
    else:
        print(f"  [!] Could not find {file}. Double-check the file name. Skipping...")

if not all_panels:
    raise ValueError("CRITICAL: No CSV files were found in this directory!")

# 3. Concatenate into one giant panel
print("\nConcatenating into Master Panel (this might take a moment)...")
master_gravity_panel = pd.concat(all_panels, ignore_index=True)

# 4. Final Export to CSV
output_name = 'MASTER_Gravity_Panel_2013_2023.csv'
print(f"Exporting to {output_name}...")

master_gravity_panel.to_csv(output_name, index=False)

print("\n--- SUCCESS! ---")
print(f"Your final regression dataset is ready: {output_name}")
print(f"Total Master Rows: {len(master_gravity_panel)}")

--- STARTING MASTER CSV PANEL MERGE ---
Loading CHN_Final_Applied_Tariffs_2013_2023.csv...
Loading IND_Final_Applied_Tariffs_2013_2023.csv...
Loading PAK_Final_Applied_Tariffs_2013_2023.csv...
Loading KAZ_Final_Applied_Tariffs_2013_2023.csv...

Concatenating into Master Panel (this might take a moment)...
Exporting to MASTER_Gravity_Panel_2013_2023.csv...

--- SUCCESS! ---
Your final regression dataset is ready: MASTER_Gravity_Panel_2013_2023.csv
Total Master Rows: 23059626

In [10]:
master_gravity_panel

,iso3_reporter,iso3_exporter,ProductCode,Year,pref,prefAVE,mfn,mfnAVE,Applied_Tariff,Applied_Tariff_AVE
0,CHN,AFG,10121,2013,0.0,0.0,0.0,0.0,0.0,0.0
1,CHN,AFG,10121,2014,0.0,0.0,0.0,0.0,0.0,0.0
2,CHN,AFG,10121,2015,0.0,0.0,0.0,0.0,0.0,0.0
3,CHN,AFG,10121,2016,0.0,0.0,0.0,0.0,0.0,0.0
4,CHN,AFG,10121,2017,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
23059621,KAZ,ZWE,970690,2019,NaN,NaN,0.0,0.0,0.0,0.0
23059622,KAZ,ZWE,970690,2020,NaN,NaN,0.0,0.0,0.0,0.0
23059623,KAZ,ZWE,970690,2021,NaN,NaN,0.0,0.0,0.0,0.0
23059624,KAZ,ZWE,970690,2022,NaN,NaN,0.0,0.0,0.0,0.0
23059625,KAZ,ZWE,970690,2023,NaN,NaN,0.0,0.0,0.0,0.0

In [11]:
import pandas as pd
import os

print("--- STARTING NOMENCODE RESCUE ---")

# 1. Helper to find MFN files
def find_mfn_file(iso, year):
    target = f"MFN_{iso}_{year}.CSV"
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f.lower() == target.lower():
                return os.path.join(root, f)
    return None

# 2. Build a Lookup Table for NomenCodes
print("Scanning raw files for NomenCodes...")
nomen_data = []
target_importers = ['CHN', 'IND', 'PAK', 'KAZ'] 

for iso in target_importers:
    for year in range(2013, 2024):
        file_path = find_mfn_file(iso, year)
        if file_path:
            # We only need to read ONE row to get the NomenCode for the whole year!
            df_temp = pd.read_csv(file_path, encoding='latin-1', nrows=1)
            if 'NomenCode' in df_temp.columns:
                nomen = df_temp['NomenCode'].iloc[0]
                nomen_data.append({'iso3_reporter': iso, 'Year': year, 'NomenCode': nomen})
            else:
                print(f"  [!] NomenCode column missing inside {file_path}")
        else:
            print(f"  [!] Could not find MFN file for {iso} {year} to extract NomenCode.")

nomen_lookup = pd.DataFrame(nomen_data)
print("\nLookup Table Built:")
print(nomen_lookup.head())

# 3. Inject into the Master Panel
print("\nLoading Master CSV Panel (this takes a moment for 23M rows)...")
master_df = pd.read_csv('MASTER_Gravity_Panel_2013_2023.csv', low_memory=False)

print("Merging NomenCode...")
master_df = pd.merge(master_df, nomen_lookup, on=['iso3_reporter', 'Year'], how='left')

# 4. Save the corrected Master Panel
print("Saving corrected Master Panel...")
master_df.to_csv('MASTER_Gravity_Panel_2013_2023.csv', index=False)

print("\n--- RESCUE COMPLETE! NomenCode restored! ---")
print(f"Final columns: {master_df.columns.tolist()}")

--- STARTING NOMENCODE RESCUE ---
Scanning raw files for NomenCodes...

Lookup Table Built:
  iso3_reporter  Year NomenCode
0           CHN  2013        H4
1           CHN  2014        H4
2           CHN  2015        H4
3           CHN  2016        H4
4           CHN  2017        H5

Loading Master CSV Panel (this takes a moment for 23M rows)...
Merging NomenCode...
Saving corrected Master Panel...

--- RESCUE COMPLETE! NomenCode restored! ---
Final columns: ['iso3_reporter', 'iso3_exporter', 'ProductCode', 'Year', 'pref', 'prefAVE', 'mfn', 'mfnAVE', 'Applied_Tariff', 'Applied_Tariff_AVE', 'NomenCode']

In [12]:
master_df

,iso3_reporter,iso3_exporter,ProductCode,Year,pref,prefAVE,mfn,mfnAVE,Applied_Tariff,Applied_Tariff_AVE,NomenCode
0,CHN,AFG,10121,2013,0.0,0.0,0.0,0.0,0.0,0.0,H4
1,CHN,AFG,10121,2014,0.0,0.0,0.0,0.0,0.0,0.0,H4
2,CHN,AFG,10121,2015,0.0,0.0,0.0,0.0,0.0,0.0,H4
3,CHN,AFG,10121,2016,0.0,0.0,0.0,0.0,0.0,0.0,H4
4,CHN,AFG,10121,2017,0.0,0.0,0.0,0.0,0.0,0.0,H5
...,...,...,...,...,...,...,...,...,...,...,...
23059621,KAZ,ZWE,970690,2019,NaN,NaN,0.0,0.0,0.0,0.0,H5
23059622,KAZ,ZWE,970690,2020,NaN,NaN,0.0,0.0,0.0,0.0,H5
23059623,KAZ,ZWE,970690,2021,NaN,NaN,0.0,0.0,0.0,0.0,H5
23059624,KAZ,ZWE,970690,2022,NaN,NaN,0.0,0.0,0.0,0.0,H6
23059625,KAZ,ZWE,970690,2023,NaN,NaN,0.0,0.0,0.0,0.0,H6

In [15]:
import pandas as pd
import numpy as np

print("--- STARTING HS17 TO HS12 HARMONIZATION ---")

# 1. Load the Concordance File (FIXED ENCODING)
print("Loading concordance table...")
conc = pd.read_csv('hs17to12.csv', dtype=str, encoding='latin-1')

# Clean up column names (stripping any accidental leading/trailing spaces in the CSV)
conc.columns = [str(c).strip() for c in conc.columns]

# Keep only the two columns we need and rename them for easy merging
conc = conc[['Product Code', 'HS 2012 Product Code']]
conc = conc.rename(columns={'Product Code': 'HS17', 'HS 2012 Product Code': 'HS12'})

# Ensure they are formatted as 6-digit strings
conc['HS17'] = conc['HS17'].str.zfill(6)
conc['HS12'] = conc['HS12'].str.zfill(6)

# Drop any duplicate mapping pairs in the concordance file itself
conc = conc.drop_duplicates()

# 2. Load the Master Panel
print("Loading Master Tariff Panel (this takes a moment)...")
df = pd.read_csv('MASTER_Gravity_Panel_2013_2023.csv', low_memory=False)
df['ProductCode'] = df['ProductCode'].astype(str).str.zfill(6)

# 3. Split the data by Nomenclature
# H4 is already HS12. We only need to touch H5 (HS17)
print("Splitting dataset by nomenclature...")
df_h4 = df[df['NomenCode'] == 'H4'].copy()
df_h5 = df[df['NomenCode'] == 'H5'].copy()

print(f"  Rows already in HS12 (H4): {len(df_h4)}")
print(f"  Rows needing conversion (H5): {len(df_h5)}")

# 4. Map the H5 rows to HS12
print("\nMapping HS17 codes back to HS12...")
df_h5_mapped = pd.merge(df_h5, conc, left_on='ProductCode', right_on='HS17', how='inner')

# Replace the ProductCode column with the mapped HS12 code
df_h5_mapped['ProductCode'] = df_h5_mapped['HS12']

# Drop the temporary mapping columns
df_h5_mapped = df_h5_mapped.drop(columns=['HS17', 'HS12'])

# 5. Recombine the dataset
print("Recombining dataset...")
df_harmonized = pd.concat([df_h4, df_h5_mapped], ignore_index=True)

# 6. Aggregate Many-to-One splits
print("Averaging tariffs for many-to-one HS splits (Fontagné Method)...")
# We group by the core identifiers and take the mean of the tariffs
numeric_cols = ['mfn', 'mfnAVE', 'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE']

df_final = df_harmonized.groupby(
    ['iso3_reporter', 'iso3_exporter', 'Year', 'ProductCode'], 
    as_index=False
)[numeric_cols].mean()

# 7. Final Export
print(f"\nExporting Harmonized CSV...")
df_final.to_csv('MASTER_Tariffs_HS12_Harmonized.csv', index=False)

print("\n--- HARMONIZATION COMPLETE! ---")
print(f"Final Harmonized Rows: {len(df_final)}")

--- STARTING HS17 TO HS12 HARMONIZATION ---
Loading concordance table...
Loading Master Tariff Panel (this takes a moment)...
Splitting dataset by nomenclature...
  Rows already in HS12 (H4): 8706609
  Rows needing conversion (H5): 10252155

Mapping HS17 codes back to HS12...
Recombining dataset...
Averaging tariffs for many-to-one HS splits (Fontagné Method)...

Exporting Harmonized CSV...

--- HARMONIZATION COMPLETE! ---
Final Harmonized Rows: 17315439

In [16]:
import pandas as pd
df_check = pd.read_csv('MASTER_Gravity_Panel_2013_2023.csv', usecols=['NomenCode'])
print(df_check['NomenCode'].value_counts(dropna=False))

NomenCode
H5    10252155
H4     8706609
H6     4100862
Name: count, dtype: int64

In [17]:
import pandas as pd
import numpy as np

print("--- STARTING ULTIMATE HS12 HARMONIZATION (H4 + H5 + H6) ---")

# ==========================================
# 1. LOAD CONCORDANCE FILES
# ==========================================
print("Loading concordance tables...")

def prep_concordance(file_path):
    # Read with latin-1 to avoid special character errors
    conc = pd.read_csv(file_path, dtype=str, encoding='latin-1')
    
    # Clean up column names
    conc.columns = [str(c).strip() for c in conc.columns]
    
    # Keep only target columns and rename them
    conc = conc[['Product Code', 'HS 2012 Product Code']]
    conc = conc.rename(columns={'Product Code': 'Source_Code', 'HS 2012 Product Code': 'HS12_Code'})
    
    # Format to 6-digit strings
    conc['Source_Code'] = conc['Source_Code'].str.zfill(6)
    conc['HS12_Code'] = conc['HS12_Code'].str.zfill(6)
    
    return conc.drop_duplicates()

conc_17_to_12 = prep_concordance('hs17to12.csv')
conc_22_to_12 = prep_concordance('hs22to12.csv')

# ==========================================
# 2. LOAD MASTER PANEL
# ==========================================
print("Loading Master Tariff Panel (23M rows)...")
df = pd.read_csv('MASTER_Gravity_Panel_2013_2023.csv', low_memory=False)
df['ProductCode'] = df['ProductCode'].astype(str).str.zfill(6)

# ==========================================
# 3. SPLIT BY NOMENCLATURE
# ==========================================
print("Splitting dataset by nomenclature...")
df_h4 = df[df['NomenCode'] == 'H4'].copy()
df_h5 = df[df['NomenCode'] == 'H5'].copy()
df_h6 = df[df['NomenCode'] == 'H6'].copy()

print(f"  Rows already in HS12 (H4): {len(df_h4)}")
print(f"  Rows needing HS17->HS12 (H5): {len(df_h5)}")
print(f"  Rows needing HS22->HS12 (H6): {len(df_h6)}")

# ==========================================
# 4. MAP TO HS12
# ==========================================
print("\nMapping H5 (HS17) codes back to HS12...")
df_h5_mapped = pd.merge(df_h5, conc_17_to_12, left_on='ProductCode', right_on='Source_Code', how='inner')
df_h5_mapped['ProductCode'] = df_h5_mapped['HS12_Code']
df_h5_mapped = df_h5_mapped.drop(columns=['Source_Code', 'HS12_Code'])

print("Mapping H6 (HS22) codes back to HS12...")
df_h6_mapped = pd.merge(df_h6, conc_22_to_12, left_on='ProductCode', right_on='Source_Code', how='inner')
df_h6_mapped['ProductCode'] = df_h6_mapped['HS12_Code']
df_h6_mapped = df_h6_mapped.drop(columns=['Source_Code', 'HS12_Code'])

# ==========================================
# 5. RECOMBINE AND AGGREGATE
# ==========================================
print("\nRecombining dataset...")
df_harmonized = pd.concat([df_h4, df_h5_mapped, df_h6_mapped], ignore_index=True)

print("Averaging tariffs for many-to-one HS splits (Fontagné Method)...")
numeric_cols = ['mfn', 'mfnAVE', 'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE']

# Group by the core bilateral-product-year identifiers and calculate the mean
df_final = df_harmonized.groupby(
    ['iso3_reporter', 'iso3_exporter', 'Year', 'ProductCode'], 
    as_index=False
)[numeric_cols].mean()

# ==========================================
# 6. FINAL EXPORT
# ==========================================
print("\nExporting Final Harmonized CSV...")
df_final.to_csv('MASTER_Tariffs_HS12_Harmonized_FULL.csv', index=False)

print("\n--- HARMONIZATION COMPLETE! ---")
print(f"Final Harmonized Rows: {len(df_final)}")

--- STARTING ULTIMATE HS12 HARMONIZATION (H4 + H5 + H6) ---
Loading concordance tables...
Loading Master Tariff Panel (23M rows)...
Splitting dataset by nomenclature...
  Rows already in HS12 (H4): 8706609
  Rows needing HS17->HS12 (H5): 10252155
  Rows needing HS22->HS12 (H6): 4100862

Mapping H5 (HS17) codes back to HS12...
Mapping H6 (HS22) codes back to HS12...

Recombining dataset...
Averaging tariffs for many-to-one HS splits (Fontagné Method)...

Exporting Final Harmonized CSV...

--- HARMONIZATION COMPLETE! ---
Final Harmonized Rows: 20941269

In [18]:
df_final

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE
0,CHN,AFG,2013,010121,0.0,0.0,0.0,0.0,0.0,0.0
1,CHN,AFG,2013,010129,10.0,10.0,0.0,0.0,0.0,0.0
2,CHN,AFG,2013,010130,5.0,5.0,0.0,0.0,0.0,0.0
3,CHN,AFG,2013,010190,10.0,10.0,0.0,0.0,0.0,0.0
4,CHN,AFG,2013,010221,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
20941264,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0
20941265,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0
20941266,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0
20941267,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0
20941268,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0

In [21]:
df = pd.read_csv('BACI/BACI_HS12_Y2013_V202601.csv')
df_10 = df.head(100)

In [28]:
df_10

       t  i   j       k      v      q
0   2013  4   8  401519  2.952  0.342
1   2013  4   8  630900  1.799  0.023
2   2013  4  12  611020  0.181  0.005
3   2013  4  20   40610  1.895  0.342
4   2013  4  20  570242  2.660  0.008
..   ... ..  ..     ...    ...    ...
95  2013  4  40   81090  0.875  0.078
96  2013  4  40   81190  1.276  0.098
97  2013  4  40   90720  1.211  0.175
98  2013  4  40   91099  0.004  0.001
99  2013  4  40  180690  0.065  0.003

[100 rows x 6 columns]

### ADD BACI

In [1]:
import pandas as pd
import numpy as np
import os

print("--- STARTING GLOBAL BACI INTEGRATION (2013-2023) ---")

# 1. LOAD CONCORDANCE & TARIFFS
print("Loading master lists and tariff panel...")
country_master = pd.read_csv('BACI_country_codes.csv')
iso_map = country_master.set_index('country_code')['country_iso3'].to_dict()

tariffs = pd.read_csv('MASTER_Tariffs_HS12_Harmonized_FULL.csv', low_memory=False)
tariffs['ProductCode'] = tariffs['ProductCode'].astype(str).str.zfill(6)
tariffs['Year'] = tariffs['Year'].astype(int)

# 2. DEFINE BACI FOLDER AND YEARS
baci_folder = 'BACI'
target_importers = ['CHN', 'IND', 'PAK', 'KAZ']
all_trade_years = []

# 3. LOOP THROUGH BACI FILES
print("Processing yearly BACI files...")
for year in range(2013, 2024):
    # Naming convention based on your 2013 file
    file_name = f"BACI_HS12_Y{year}_V202601.csv"
    path = os.path.join(baci_folder, file_name)
    
    if os.path.exists(path):
        print(f" -> Reading {file_name}...")
        trade = pd.read_csv(path)
        
        # Map columns and translate ISOs
        trade['Year'] = trade['t'].astype(int)
        trade['iso3_exporter'] = trade['i'].map(iso_map)
        trade['iso3_reporter'] = trade['j'].map(iso_map)
        trade['ProductCode'] = trade['k'].astype(str).str.zfill(6)
        
        # Filter for your importers before merging to save RAM
        trade = trade[trade['iso3_reporter'].isin(target_importers)].copy()
        
        # Calculate Unit Value
        trade['TradeValue_1000USD'] = trade['v']
        trade['Quantity'] = trade['q']
        trade['Unit_Value'] = np.where(trade['Quantity'] > 0, 
                                       trade['TradeValue_1000USD'] / trade['Quantity'], 
                                       np.nan)
        
        all_trade_years.append(trade[['Year', 'iso3_exporter', 'iso3_reporter', 'ProductCode', 
                                      'TradeValue_1000USD', 'Quantity', 'Unit_Value']])
    else:
        print(f" [!] Skipping {year}: File not found.")

# Combine all trade data
master_trade = pd.concat(all_trade_years, ignore_index=True)

# 4. FINAL MERGE (Preserving all Tariff Columns)
print("\nMerging with Tariff Panel (Preserving all policy columns)...")
final_df = pd.merge(
    tariffs, 
    master_trade, 
    on=['Year', 'iso3_reporter', 'iso3_exporter', 'ProductCode'], 
    how='left'
)

# 5. PPML ZERO-FILL & TRANSFORMATIONS
print("Finalizing variables...")
final_df['TradeValue_1000USD'] = final_df['TradeValue_1000USD'].fillna(0)
final_df['Quantity'] = final_df['Quantity'].fillna(0)
final_df['ln_tariff'] = np.log(1 + (final_df['Applied_Tariff_AVE'] / 100))

# 6. EXPORT
print("Exporting final datasets...")
final_df.to_csv('ULTIMATE_Gravity_Panel_HS12_Full.csv', index=False)
final_df.to_stata('ULTIMATE_Gravity_Panel_HS12_Full.dta', write_index=False, version=118)

print("\n--- DONE! ---")
print(f"Final Row Count: {len(final_df)}")

--- STARTING GLOBAL BACI INTEGRATION (2013-2023) ---
Loading master lists and tariff panel...
Processing yearly BACI files...
 -> Reading BACI_HS12_Y2013_V202601.csv...
 -> Reading BACI_HS12_Y2014_V202601.csv...
 -> Reading BACI_HS12_Y2015_V202601.csv...
 -> Reading BACI_HS12_Y2016_V202601.csv...
 -> Reading BACI_HS12_Y2017_V202601.csv...
 -> Reading BACI_HS12_Y2018_V202601.csv...
 -> Reading BACI_HS12_Y2019_V202601.csv...
 -> Reading BACI_HS12_Y2020_V202601.csv...
 -> Reading BACI_HS12_Y2021_V202601.csv...
 -> Reading BACI_HS12_Y2022_V202601.csv...
 -> Reading BACI_HS12_Y2023_V202601.csv...

Merging with Tariff Panel (Preserving all policy columns)...
Finalizing variables...
Exporting final datasets...

--- DONE! ---
Final Row Count: 20941269

In [2]:
final_df

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff
0,CHN,AFG,2013,010121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
1,CHN,AFG,2013,010129,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
2,CHN,AFG,2013,010130,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
3,CHN,AFG,2013,010190,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
4,CHN,AFG,2013,010221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941264,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559
20941265,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559
20941266,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559
20941267,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559
20941268,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559

In [1]:
import pandas as pd
import numpy as np

# 1. Load the final harmonized tariff panel
# This is the version with 20,941,269 rows
input_csv = 'MASTER_Tariffs_HS12_Harmonized_FULL.csv'
print(f"Loading {input_csv}...")
df = pd.read_csv(input_csv, low_memory=False)

# 2. Optimize Data Types for Stata
print("Optimizing data types to save memory and ensure Stata compatibility...")

# Convert identifiers to 'category' to shrink file size significantly
# This also bypasses common Pandas-to-Stata string length issues
for col in ['iso3_reporter', 'iso3_exporter', 'ProductCode']:
    if col in df.columns:
        df[col] = df[col].astype(str).astype('category')

# Downcast floats to float32 (reduces memory usage by 50% vs float64)
float_cols = ['mfn', 'mfnAVE', 'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE']
for col in float_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('float32')

# Downcast Year to int16
if 'Year' in df.columns:
    df['Year'] = df['Year'].astype('int16')

# 3. Export to Stata .dta
output_dta = 'MASTER_Tariffs_HS12_Harmonized_FULL.dta'
print(f"Exporting to {output_dta}... This may take a few minutes.")

try:
    # version 118 is the standard for modern Stata (Stata 14+)
    df.to_stata(output_dta, write_index=False, version=118)
    print("\n--- SUCCESS! ---")
    print(f"File saved as: {output_dta}")
except Exception as e:
    print(f"\nStandard export failed: {e}")
    print("Attempting export with pyreadstat...")
    import pyreadstat
    pyreadstat.write_dta(df, output_dta)
    print("Saved successfully using pyreadstat.")

Loading MASTER_Tariffs_HS12_Harmonized_FULL.csv...
Optimizing data types to save memory and ensure Stata compatibility...
Exporting to MASTER_Tariffs_HS12_Harmonized_FULL.dta... This may take a few minutes.

Standard export failed: Stata value labels for a single variable must have a combined length less than 32,000 characters.
Attempting export with pyreadstat...
Saved successfully using pyreadstat.

In [30]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (1.2 kB)
Collecting narwhals>=2.10.1 (from pyreadstat)
  Downloading narwhals-2.17.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from pyreadstat) (2.1.3)
Downloading pyreadstat-1.3.3-cp313-cp313-macosx_11_0_arm64.whl (522 kB)
Downloading narwhals-2.17.0-py3-none-any.whl (444 kB)
Installing collected packages: narwhals, pyreadstat
  Attempting uninstall: narwhals
    Found existing installation: narwhals 1.31.0
    Uninstalling narwhals-1.31.0:
      Successfully uninstalled narwhals-1.31.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pyreadstat]
Successfully installed narwhals-2.17.0 pyreadstat-1.3.3

In [1]:
import pandas as pd
df = pd.read_csv('ULTIMATE_Gravity_Panel_HS12_Full.csv')

In [2]:
df.describe()

,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff
count,2.094127e+07,2.094127e+07,2.094022e+07,2.094022e+07,2.092846e+07,2.092846e+07,2.094127e+07,2.094127e+07,2.094127e+07,2.094127e+07,1.110295e+06,2.094127e+07
mean,2.017844e+03,5.244541e+05,9.230650e+00,9.371548e+00,5.030347e+00,5.042485e+00,3.216545e+00,3.165302e+00,4.009690e+02,5.308238e+02,7.045813e+02,2.999498e-02
std,3.180863e+00,2.833530e+05,9.664965e+00,2.178670e+01,8.890676e+00,9.100348e+00,5.198446e+00,5.322120e+00,4.630342e+04,1.444480e+05,5.627191e+04,4.697575e-02
min,2.013000e+03,1.012100e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.468750e-05,0.000000e+00
25%,2.015000e+03,2.909500e+05,5.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.815494e+00,0.000000e+00
50%,2.018000e+03,5.407430e+05,7.500000e+00,7.500000e+00,1.880000e+00,1.880000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.054592e+01,0.000000e+00
75%,2.021000e+03,8.301600e+05,1.000000e+01,1.000000e+01,8.250000e+00,7.500000e+00,5.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,3.711174e+01,4.879016e-02
max,2.023000e+03,9.999990e+05,1.500000e+02,3.000000e+03,9.000000e+01,5.111000e+02,1.250000e+02,5.111000e+02,5.043822e+07,3.064859e+08,2.742224e+07,1.810090e+00

In [ ]:
df_gravity = pd.read_csv('CEPII gravity.csv', low_memory=False)

In [5]:
df_gravity.head()

,year,country_id_o,country_id_d,iso3_o,iso3_d,iso3num_o,iso3num_d,country_exists_o,country_exists_d,gmt_offset_2020_o,...,entry_time_o,entry_time_d,entry_tp_o,entry_tp_d,tradeflow_comtrade_o,tradeflow_comtrade_d,tradeflow_baci,manuf_tradeflow_baci,tradeflow_imf_o,tradeflow_imf_d
0,1948,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1949,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1950,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1951,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1952,ABW,ABW,ABW,ABW,533.0,533.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_gravity.head(10).to_csv('gravity_preview.csv')

In [7]:
import pandas as pd
import numpy as np
import pyreadstat

print("--- ADDING ALL CEPII GRAVITY CONTROLS ---")

# 1. Load the ultimate trade and tariff panel
print("Loading ultimate trade panel (21M rows)...")
final_df = pd.read_csv('ULTIMATE_Gravity_Panel_HS12_Full.csv', low_memory=False)

# 2. Extract the full suite of gravity variables
# We include distance, borders, language, history, and the RTA dummy
gravity_vars = [
    'year', 'iso3_o', 'iso3_d', 
    'dist', 'contig', 'comlang_off', 'comcol', 'fta_wto'
]

print("Preparing CEPII variables...")
gravity_slim = df_gravity[gravity_vars].copy()

# Ensure matching data types for a clean merge
gravity_slim['year'] = gravity_slim['year'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)

# 3. Perform the Left Merge
print("Merging controls into the main dataset...")
final_df = pd.merge(
    final_df, 
    gravity_slim, 
    left_on=['Year', 'iso3_exporter', 'iso3_reporter'], 
    right_on=['year', 'iso3_o', 'iso3_d'], 
    how='left'
)

# 4. Clean up and Rename
print("Cleaning up columns...")
final_df = final_df.drop(columns=['year', 'iso3_o', 'iso3_d'])

# Rename fta_wto to 'rta' for easier Stata syntax
final_df = final_df.rename(columns={'fta_wto': 'rta'})

# Fill missing dummy variables with 0 (assuming no agreement/border if missing)
dummy_cols = ['rta', 'contig', 'comlang_off', 'comcol']
for col in dummy_cols:
    final_df[col] = final_df[col].fillna(0)

# 5. Export the Final Upgraded Dataset
print("Exporting ULTIMATE_Gravity_Dataset_With_Controls...")

# Save to CSV for backup
final_df.to_csv('ULTIMATE_Gravity_Dataset_With_Controls.csv', index=False)

# Optimize for Stata (.dta)
print("Optimizing data types for Stata export...")
for col in ['iso3_reporter', 'iso3_exporter', 'ProductCode']:
    final_df[col] = final_df[col].astype(str)

# Ensure numeric columns are floats to save memory
float_cols = ['Applied_Tariff_AVE', 'TradeValue_1000USD', 'dist']
for col in float_cols:
    if col in final_df.columns:
        final_df[col] = pd.to_numeric(final_df[col], errors='coerce').astype('float32')

# Downcast dummies to integers
for col in dummy_cols:
    final_df[col] = final_df[col].astype('int8')

print("Saving to Stata format (.dta)...")
pyreadstat.write_dta(final_df, 'ULTIMATE_Gravity_Dataset_With_Controls.dta', version=14)

print("\n--- DONE! ---")
print("Your dataset now contains the full set of Gravity controls.")

--- ADDING ALL CEPII GRAVITY CONTROLS ---
Loading ultimate trade panel (21M rows)...
Preparing CEPII variables...
Merging controls into the main dataset...
Cleaning up columns...
Exporting ULTIMATE_Gravity_Dataset_With_Controls...
Optimizing data types for Stata export...
Saving to Stata format (.dta)...

--- DONE! ---
Your dataset now contains the full set of Gravity controls.

In [8]:
# Check how many rows successfully matched distance data
missing_distance = final_df['dist'].isnull().sum()
total_rows = len(final_df)
print(f"Total Rows: {total_rows}")
print(f"Rows missing distance data: {missing_distance} ({(missing_distance/total_rows)*100:.2f}%)")

# Look at a quick snapshot of the new columns
print(final_df[['iso3_exporter', 'iso3_reporter', 'Year', 'dist', 'rta']].head(10))

Total Rows: 22421231
Rows missing distance data: 5500396 (24.53%)
  iso3_exporter iso3_reporter  Year    dist  rta
0           AFG           CHN  2013  4852.0    0
1           AFG           CHN  2013  4852.0    0
2           AFG           CHN  2013  4852.0    0
3           AFG           CHN  2013  4852.0    0
4           AFG           CHN  2013  4852.0    0
5           AFG           CHN  2013  4852.0    0
6           AFG           CHN  2013  4852.0    0
7           AFG           CHN  2013  4852.0    0
8           AFG           CHN  2013  4852.0    0
9           AFG           CHN  2013  4852.0    0

# Correction

In [10]:
import pandas as pd
import numpy as np
import pyreadstat

print("--- FIXING CEPII GRAVITY MERGE (ROBUST STATIC EXTRACTION) ---")

# 1. Load your ultimate trade panel
print("Loading ultimate trade panel...")
final_df = pd.read_csv('ULTIMATE_Gravity_Panel_HS12_Full.csv', low_memory=False)

# 2. Extract Static Geography Properly
print("Extracting clean static geography...")
static_vars = ['iso3_o', 'iso3_d', 'dist', 'contig', 'comlang_off', 'comcol']
gravity_static = df_gravity[static_vars].copy()

# CRITICAL FIX: Drop rows where distance is blank BEFORE dropping duplicates
gravity_static = gravity_static.dropna(subset=['dist'])

# Now, keep one clean, fully populated row per country pair
gravity_static = gravity_static.drop_duplicates(subset=['iso3_o', 'iso3_d'])

# Merge Static Variables
final_df = pd.merge(
    final_df, 
    gravity_static, 
    left_on=['iso3_exporter', 'iso3_reporter'], 
    right_on=['iso3_o', 'iso3_d'], 
    how='left'
)
final_df = final_df.drop(columns=['iso3_o', 'iso3_d'])

# 3. Extract and Merge Time-Varying RTAs
print("Processing time-varying RTAs...")
rta_vars = ['year', 'iso3_o', 'iso3_d', 'fta_wto']
gravity_rta = df_gravity[rta_vars].copy()
gravity_rta['year'] = gravity_rta['year'].astype(int)

final_df = pd.merge(
    final_df, 
    gravity_rta, 
    left_on=['Year', 'iso3_exporter', 'iso3_reporter'], 
    right_on=['year', 'iso3_o', 'iso3_d'], 
    how='left'
)
final_df = final_df.drop(columns=['year', 'iso3_o', 'iso3_d'])
final_df = final_df.rename(columns={'fta_wto': 'rta'})

# 4. Forward-Fill RTAs
print("Forward-filling missing RTAs...")
final_df = final_df.sort_values(['iso3_exporter', 'iso3_reporter', 'ProductCode', 'Year'])
final_df['rta'] = final_df.groupby(['iso3_exporter', 'iso3_reporter'])['rta'].ffill()

# Fill dummy variable NAs with 0
dummy_cols = ['rta', 'contig', 'comlang_off', 'comcol']
for col in dummy_cols:
    final_df[col] = final_df[col].fillna(0)

# 5. VERIFICATION
missing_dist = final_df['dist'].isnull().sum()
print(f"\n--- VERIFICATION ---")
print(f"Total Rows: {len(final_df)}")
print(f"Rows missing distance: {missing_dist} ({(missing_dist/len(final_df))*100:.2f}%)")

if missing_dist > 0:
    missing_exporters = final_df[final_df['dist'].isnull()]['iso3_exporter'].unique()
    print(f"\nExporters failing to match in CEPII Gravity: {list(missing_exporters)[:15]}")
    print("(These are usually synthetic codes like 'Free Zones' or tiny island territories)")

# 6. Final Export
print("\nOptimizing and exporting to Stata...")
for col in ['iso3_reporter', 'iso3_exporter', 'ProductCode']:
    final_df[col] = final_df[col].astype(str)

float_cols = ['Applied_Tariff_AVE', 'TradeValue_1000USD', 'dist']
for col in float_cols:
    if col in final_df.columns:
        final_df[col] = pd.to_numeric(final_df[col], errors='coerce').astype('float32')

for col in dummy_cols:
    final_df[col] = final_df[col].astype('int8')

pyreadstat.write_dta(final_df, 'ULTIMATE_Gravity_Dataset_With_Controls.dta', version=14)
print("Saved successfully!")

--- FIXING CEPII GRAVITY MERGE (ROBUST STATIC EXTRACTION) ---
Loading ultimate trade panel...
Extracting clean static geography...
Processing time-varying RTAs...
Forward-filling missing RTAs...

--- VERIFICATION ---
Total Rows: 22421231
Rows missing distance: 417557 (1.86%)

Exporters failing to match in CEPII Gravity: ['ATF', 'BVT', 'HMD', 'MNT', 'SGS', 'USP', 'VIR']
(These are usually synthetic codes like 'Free Zones' or tiny island territories)

Optimizing and exporting to Stata...
Saved successfully!

In [1]:
import pandas as pd
df = pd.read_csv('ULTIMATE_Gravity_Panel_HS12_Full.csv')

# Assuming your dataframe is named 'df'

# 1. Calculate the total trade for each Exporter-Product combination
# The transform('sum') function calculates the sum per group and assigns 
# that total to every row belonging to that group.
df['exporter_capacity_flag'] = df.groupby(['iso3_exporter', 'ProductCode'])['TradeValue_1000USD'].transform('sum')

# 2. Filter the dataset to keep only the rows where the exporter has 
# exported the product at least once (total trade > 0)
df_clean = df[df['exporter_capacity_flag'] > 0].copy()

# 3. Drop the temporary flag column to save memory
df_clean = df_clean.drop(columns=['exporter_capacity_flag'])

# Print the results to see how many rows were dropped
print(f"Original rows: {len(df)}")
print(f"Rows after dropping zero-capacity exporters: {len(df_clean)}")
print(f"Total rows dropped: {len(df) - len(df_clean)}")

Original rows: 20941269
Rows after dropping zero-capacity exporters: 3961964
Total rows dropped: 16979305

In [3]:
df_clean.to_csv('regression dataset excl zero.csv')

In [4]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in /opt/anaconda3/lib/python3.13/site-packages (1.3.3)
Requirement already satisfied: narwhals>=2.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from pyreadstat) (2.17.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from pyreadstat) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [7]:
pyreadstat.write_dta(df_clean, 'regression dataset excl zero.dta', version=14)

In [6]:
import pyreadstat

In [8]:
df

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff,exporter_capacity_flag
0,CHN,AFG,2013,10121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
1,CHN,AFG,2013,10129,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
2,CHN,AFG,2013,10130,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
3,CHN,AFG,2013,10190,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
4,CHN,AFG,2013,10221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941264,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941265,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,7.609
20941266,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941267,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941268,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,73.519

In [12]:
df['Unit_Value'][1381343]

np.float64(57.0)

In [13]:
df

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff,exporter_capacity_flag
0,CHN,AFG,2013,10121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
1,CHN,AFG,2013,10129,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
2,CHN,AFG,2013,10130,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
3,CHN,AFG,2013,10190,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
4,CHN,AFG,2013,10221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941264,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941265,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,7.609
20941266,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941267,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000
20941268,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,73.519

In [26]:

# Optional: make sure trade values are numeric
df["TradeValue_1000USD"] = pd.to_numeric(df["TradeValue_1000USD"], errors="coerce").fillna(0)

# Define keys for Fontagné-style zero filtering
# exporter i = iso3_exporter
# product k = ProductCode
group_cols = ["iso3_exporter", "ProductCode"]

# Step 1: for each exporter-product pair, check whether it ever has a positive trade flow
# anywhere in the sample period and across all importers in your dataset
df["ever_positive_exporter_product"] = (
    df.groupby(group_cols)["TradeValue_1000USD"]
      .transform(lambda x: (x > 0).any())
)

# Step 2: keep:
# - all rows with positive trade
# - zero rows only if the exporter-product pair is active somewhere in the sample
df_filtered = df[
    (df["TradeValue_1000USD"] > 0) |
    (
        (df["TradeValue_1000USD"] == 0) &
        (df["ever_positive_exporter_product"])
    )
].copy()

# Step 3: drop helper column
df_filtered.drop(columns=["ever_positive_exporter_product"], inplace=True)

print("Original rows:", len(df))
print("Filtered rows:", len(df_filtered))
print("Dropped rows:", len(df) - len(df_filtered))

Original rows: 20941269
Filtered rows: 3961964
Dropped rows: 16979305

In [27]:
# Exporter-product pairs with no positive trade left in filtered file
check = (
    df_filtered.groupby(["iso3_exporter", "ProductCode"])["TradeValue_1000USD"]
    .max()
    .reset_index()
)

bad_pairs = check[check["TradeValue_1000USD"] <= 0]
print("Remaining exporter-product pairs with no positive trade:", len(bad_pairs))

Remaining exporter-product pairs with no positive trade: 0

In [29]:
df_filtered.to_csv("regression dataset fixed.csv", index=False)

In [28]:
df_filtered = df_filtered.rename(columns={
    'iso3_reporter': 'importer (j)',
    'iso3_exporter': 'exporter (i)',
    'Year': 'year (t)',
    'ProductCode': 'hs6 (k)',
    'TradeValue_1000USD': 'trade_value in 1000',
    'Quantity': 'quantity',
    'Unit_Value': 'unit_value'
})
df_filtered

,importer (j),exporter (i),year (t),hs6 (k),mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,trade_value in 1000,quantity,unit_value,ln_tariff,exporter_capacity_flag
12,CHN,AFG,2013,10410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,2577.048
26,CHN,AFG,2013,10620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.091
30,CHN,AFG,2013,10639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,2.911
31,CHN,AFG,2013,10641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,1486.102
33,CHN,AFG,2013,10690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,33.751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941261,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,10.813
20941262,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,412.011
20941263,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,9.308
20941265,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,7.609
20941268,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,73.519

In [31]:
df_filtered

,importer (j),exporter (i),year (t),hs6 (k),mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,trade_value in 1000,quantity,unit_value,ln_tariff,exporter_capacity_flag
12,CHN,AFG,2013,10410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,2577.048
26,CHN,AFG,2013,10620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.091
30,CHN,AFG,2013,10639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,2.911
31,CHN,AFG,2013,10641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,1486.102
33,CHN,AFG,2013,10690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,33.751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941261,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,10.813
20941262,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,412.011
20941263,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,9.308
20941265,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,7.609
20941268,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,73.519

In [34]:
df_filtered.columns

Index(['importer (j)', 'exporter (i)', 'year (t)', 'hs6 (k)', 'mfn', 'mfnAVE',
       'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE',
       'trade_value in 1000', 'quantity', 'unit_value', 'ln_tariff',
       'exporter_capacity_flag'],
      dtype='object')

In [38]:
import pandas as pd
import numpy as np
import pyreadstat

stata_df = df_filtered.copy()

# String variables
for col in ["importer (j)", "exporter (i)"]:
    if col in stata_df.columns:
        stata_df[col] = stata_df[col].astype(str)

# Keep HS6 as string to preserve leading zeros
if "hs6 (k)" in stata_df.columns:
    stata_df["hs6 (k)"] = (
        stata_df["hs6 (k)"]
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
        .str.zfill(6)
    )

# Year as numeric integer if possible
if "year (t)" in stata_df.columns:
    stata_df["year (t)"] = pd.to_numeric(stata_df["year (t)"], errors="coerce")
    stata_df["year (t)"] = stata_df["year (t)"].astype("Int32")

# Treat exporter_capacity_flag as numeric, not Int32
if "exporter_capacity_flag" in stata_df.columns:
    stata_df["exporter_capacity_flag"] = pd.to_numeric(
        stata_df["exporter_capacity_flag"], errors="coerce"
    ).astype("float64")

# Other numeric columns
numeric_cols = [
    "mfn",
    "mfnAVE",
    "pref",
    "prefAVE",
    "Applied_Tariff",
    "Applied_Tariff_AVE",
    "trade_value in 1000",
    "quantity",
    "unit_value",
    "ln_tariff"
]

for col in numeric_cols:
    if col in stata_df.columns:
        stata_df[col] = pd.to_numeric(stata_df[col], errors="coerce").astype("float64")

print(stata_df.dtypes)

# Temporary Stata-safe names for export only
export_df = stata_df.copy()
export_df.columns = [
    "importer_j",
    "exporter_i",
    "year_t",
    "hs6_k",
    "mfn",
    "mfnAVE",
    "pref",
    "prefAVE",
    "Applied_Tariff",
    "Applied_Tariff_AVE",
    "trade_value_1000",
    "quantity",
    "unit_value",
    "ln_tariff",
    "exporter_capacity_flag"
]

pyreadstat.write_dta(
    export_df,
    "dataset_filtered_fontagne_zeros.dta",
    version=15
)

print("Saved: dataset_filtered_fontagne_zeros.dta")

importer (j)               object
exporter (i)               object
year (t)                    Int32
hs6 (k)                    object
mfn                       float64
mfnAVE                    float64
pref                      float64
prefAVE                   float64
Applied_Tariff            float64
Applied_Tariff_AVE        float64
trade_value in 1000       float64
quantity                  float64
unit_value                float64
ln_tariff                 float64
exporter_capacity_flag    float64
dtype: object
Saved: dataset_filtered_fontagne_zeros.dta

In [39]:
import pandas as pd
import numpy as np
import pyreadstat

stata_df = df_filtered.copy()

# String variables
for col in ["importer (j)", "exporter (i)"]:
    if col in stata_df.columns:
        stata_df[col] = stata_df[col].astype(str)

# HS6 as string
if "hs6 (k)" in stata_df.columns:
    stata_df["hs6 (k)"] = (
        stata_df["hs6 (k)"]
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
        .str.zfill(6)
    )

# Year
if "year (t)" in stata_df.columns:
    stata_df["year (t)"] = pd.to_numeric(stata_df["year (t)"], errors="coerce").astype("float64")

# Numeric variables
numeric_cols = [
    "mfn",
    "mfnAVE",
    "pref",
    "prefAVE",
    "Applied_Tariff",
    "Applied_Tariff_AVE",
    "trade_value in 1000",
    "quantity",
    "unit_value",
    "ln_tariff",
    "exporter_capacity_flag"
]

for col in numeric_cols:
    if col in stata_df.columns:
        stata_df[col] = pd.to_numeric(stata_df[col], errors="coerce").astype("float64")

# Temporary Stata-safe names
export_df = stata_df.copy()
export_df.columns = [
    "importer_j",
    "exporter_i",
    "year_t",
    "hs6_k",
    "mfn",
    "mfnAVE",
    "pref",
    "prefAVE",
    "Applied_Tariff",
    "Applied_Tariff_AVE",
    "trade_value_1000",
    "quantity",
    "unit_value",
    "ln_tariff",
    "exporter_capacity_flag"
]

# Save in older Stata format
pyreadstat.write_dta(
    export_df,
    "dataset_filtered_fontagne_zeros_v12.dta",
    version=12
)

print("Saved: dataset_filtered_fontagne_zeros_v12.dta")

Saved: dataset_filtered_fontagne_zeros_v12.dta

In [40]:
df

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff,exporter_capacity_flag,ever_positive_exporter_product
0,CHN,AFG,2013,10121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000,False
1,CHN,AFG,2013,10129,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000,False
2,CHN,AFG,2013,10130,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000,False
3,CHN,AFG,2013,10190,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000,False
4,CHN,AFG,2013,10221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20941264,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000,False
20941265,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,7.609,True
20941266,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000,False
20941267,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,0.000,False
20941268,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,73.519,True

In [34]:
df = pd.read_csv('ULTIMATE_Gravity_Dataset_With_Controls.csv')
df

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,10121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,10129,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,10130,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,10190,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,10221,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22421226,PAK,PAK,2023,970200,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421227,PAK,PAK,2023,970300,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421228,PAK,PAK,2023,970400,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421229,PAK,PAK,2023,970500,3.0,3.0,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421230,PAK,PAK,2023,970600,3.0,3.0,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [35]:

# Optional: make sure trade values are numeric
df["TradeValue_1000USD"] = pd.to_numeric(df["TradeValue_1000USD"], errors="coerce").fillna(0)

# Define keys for Fontagné-style zero filtering
# exporter i = iso3_exporter
# product k = ProductCode
group_cols = ["iso3_exporter", "ProductCode"]

# Step 1: for each exporter-product pair, check whether it ever has a positive trade flow
# anywhere in the sample period and across all importers in your dataset
df["ever_positive_exporter_product"] = (
    df.groupby(group_cols)["TradeValue_1000USD"]
      .transform(lambda x: (x > 0).any())
)

# Step 2: keep:
# - all rows with positive trade
# - zero rows only if the exporter-product pair is active somewhere in the sample
df_filtered = df[
    (df["TradeValue_1000USD"] > 0) |
    (
        (df["TradeValue_1000USD"] == 0) &
        (df["ever_positive_exporter_product"])
    )
].copy()

# Step 3: drop helper column
df_filtered.drop(columns=["ever_positive_exporter_product"], inplace=True)

print("Original rows:", len(df))
print("Filtered rows:", len(df_filtered))
print("Dropped rows:", len(df) - len(df_filtered))

Original rows: 22421231
Filtered rows: 4624442
Dropped rows: 17796789

In [36]:
df_filtered

,iso3_reporter,iso3_exporter,Year,ProductCode,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,TradeValue_1000USD,Quantity,Unit_Value,ln_tariff,dist,contig,comlang_off,comcol,rta
12,CHN,AFG,2013,10410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
26,CHN,AFG,2013,10620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
30,CHN,AFG,2013,10639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
31,CHN,AFG,2013,10641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
33,CHN,AFG,2013,10690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22421223,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
22421224,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421225,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421227,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421230,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [37]:
df_filtered = df_filtered.rename(columns={
    'iso3_reporter': 'j',
    'iso3_exporter': 'i',
    'Year': 't',
    'ProductCode': 'k',
    'TradeValue_1000USD': 'value_1000usd',
    'Quantity': 'quantity',
    'Unit_Value': 'unit_value'
})
df_filtered

,j,i,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
12,CHN,AFG,2013,10410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
26,CHN,AFG,2013,10620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
30,CHN,AFG,2013,10639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
31,CHN,AFG,2013,10641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
33,CHN,AFG,2013,10690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22421223,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
22421224,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421225,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421227,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421230,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [48]:
import pandas as pd
import numpy as np
import pyreadstat

stata_df = df_filtered.copy()

# First check columns
print("Columns before export:")
print(stata_df.columns.tolist())

# Drop accidental index columns if present
stata_df = stata_df.drop(columns=["Unnamed: 0"], errors="ignore")

# Convert string variables
for col in ["importer", "exporter"]:
    if col in stata_df.columns:
        stata_df[col] = stata_df[col].astype(str)

# Keep HS6 as string
if "hs6" in stata_df.columns:
    stata_df["hs6"] = (
        stata_df["hs6"]
        .astype(str)
        .str.replace(r"\.0$", "", regex=True)
        .str.zfill(6)
    )

# Convert year
if "year" in stata_df.columns:
    stata_df["year"] = pd.to_numeric(stata_df["year"], errors="coerce").astype("float64")

# Convert numeric variables only if present
numeric_cols = [
    "mfn",
    "mfnAVE",
    "pref",
    "prefAVE",
    "Applied_Tariff",
    "Applied_Tariff_AVE",
    "trade_value in 1000",
    "quantity",
    "unit_value",
    "ln_tariff",
    "rta"
]

for col in numeric_cols:
    if col in stata_df.columns:
        stata_df[col] = pd.to_numeric(stata_df[col], errors="coerce").astype("float64")

# Rename only existing columns
rename_map = {
    "trade_value in 1000": "trade_value_1000"
}

export_df = stata_df.rename(columns=rename_map).copy()

print("Columns to export:")
print(export_df.columns.tolist())
print(export_df.dtypes)

# Save to Stata
pyreadstat.write_dta(
    export_df,
    "dataset_FINAL.dta",
    version=12
)

print("Saved: dataset_FINAL.dta")

Columns before export:
['importer', 'exporter', 'year', 'hs6', 'mfn', 'mfnAVE', 'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE', 'trade_value in 1000', 'quantity', 'unit_value', 'ln_tariff', 'dist', 'contig', 'comlang_off', 'comcol', 'rta']
Columns to export:
['importer', 'exporter', 'year', 'hs6', 'mfn', 'mfnAVE', 'pref', 'prefAVE', 'Applied_Tariff', 'Applied_Tariff_AVE', 'trade_value_1000', 'quantity', 'unit_value', 'ln_tariff', 'dist', 'contig', 'comlang_off', 'comcol', 'rta']
importer               object
exporter               object
year                  float64
hs6                    object
mfn                   float64
mfnAVE                float64
pref                  float64
prefAVE               float64
Applied_Tariff        float64
Applied_Tariff_AVE    float64
trade_value_1000      float64
quantity              float64
unit_value            float64
ln_tariff             float64
dist                  float64
contig                float64
comlang_off           float64
comcol                float64
rta                   float64
dtype: object
Saved: dataset_FINAL.dta

In [38]:
df_filtered.to_csv('DATASET_FOR_UPDATE_APRIL28.csv', index=False)

In [45]:
df_filtered.dtypes

j                      object
i                      object
t                       int64
k                       int64
mfn                   float64
mfnAVE                float64
pref                  float64
prefAVE               float64
Applied_Tariff        float64
Applied_Tariff_AVE    float64
value_1000usd         float64
quantity              float64
unit_value            float64
ln_tariff             float64
dist                  float64
contig                float64
comlang_off           float64
comcol                float64
rta                   float64
dtype: object

In [47]:
import pandas as pd


df_filtered["k"] = df_filtered["k"].astype(str)

# Count values with length == 5
count_len5 = (df_filtered["k"].str.len() == 5).sum()

print("Number of k values with length 5:", count_len5)

Number of k values with length 5: 297411

In [48]:
# Add leading zero only where length == 5
df_filtered.loc[df_filtered["k"].str.len() == 5, "k"] = "0" + df_filtered["k"]

print(df_filtered["k"].str.len().value_counts())

k
6    4624442
Name: count, dtype: int64

In [49]:
df_filtered.to_csv('DATASET_FOR_UPDATE_APRIL28.csv', index=False)

In [52]:
df_filtered['ln_tariff'].isna().sum()

np.int64(0)

In [57]:
df_filtered.rename(columns= {'j':'j_iso',
                    'i':'i_iso'}, inplace=True)

In [60]:
df_filtered.to_csv('thesis_may.csv', index=False)

In [63]:
df = pd.read_csv("thesis_may.csv", dtype={"i_iso": str, "j_iso": str, "k": str})
df

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4624437,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
4624438,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624439,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624440,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624441,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [62]:
df_filtered

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
12,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
26,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
30,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
31,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
33,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22421223,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
22421224,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421225,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421227,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
22421230,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [81]:
import pandas as pd

# Load datasets
df = pd.read_csv("thesis_may.csv", dtype={"i_iso": str, "j_iso": str, "k": str})
update = pd.read_csv("DATASET_FOR_UPDATE_APRIL28.csv", dtype={"i_iso": str, "j_iso": str, "k": str})

# --- Standardize keys ---
for d in [df, update]:
    d["i_iso"] = d["i_iso"].str.upper().str.strip()
    d["j_iso"] = d["j_iso"].str.upper().str.strip()
    d["k"] = d["k"].str.zfill(6)
    d["t"] = d["t"].astype(int)

# Columns to update
cols = ["ln_tariff", "rta", "contig", "comlang_off", "comcol"]

# Keep only necessary columns in update dataset
update_small = update[["i_iso", "j_iso", "t", "k"] + cols].copy()

# Merge (left join to preserve master dataset)
merged = df.merge(
    update_small,
    on=["i_iso", "j_iso", "t", "k"],
    how="left",
    suffixes=("", "_new")
)

# --- Fill missing values only ---
for col in cols:
    merged[col] = merged[col].fillna(merged[f"{col}_new"])

# Drop auxiliary columns
merged = merged.drop(columns=[f"{col}_new" for col in cols])


# --- Diagnostics ---
print("Remaining missing values:")
print(merged[cols].isna().sum())
merged

Remaining missing values:
ln_tariff      0
rta            0
contig         0
comlang_off    0
comcol         0
dtype: int64

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048801,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
6048802,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048803,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048804,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048805,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [82]:
df

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4624437,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
4624438,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624439,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624440,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
4624441,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [79]:
merged

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048801,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
6048802,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048803,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048804,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048805,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [84]:
# Ensure key identifiers are proper strings
merged["i_iso"] = merged["i_iso"].astype(str)
merged["j_iso"] = merged["j_iso"].astype(str)
merged["k"] = merged["k"].astype(str).str.zfill(6)

# (Optional but recommended) enforce ISO lengths
merged["i_iso"] = merged["i_iso"].str[:3]
merged["j_iso"] = merged["j_iso"].str[:3]

merged

,j_iso,i_iso,t,k,mfn,mfnAVE,pref,prefAVE,Applied_Tariff,Applied_Tariff_AVE,value_1000usd,quantity,unit_value,ln_tariff,dist,contig,comlang_off,comcol,rta
0,CHN,AFG,2013,010410,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
1,CHN,AFG,2013,010620,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
2,CHN,AFG,2013,010639,8.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
3,CHN,AFG,2013,010641,5.00,5.00,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
4,CHN,AFG,2013,010690,3.33,3.33,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,4852.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048801,PAK,PAK,2023,961900,18.20,18.20,5.0,5.0,5.0,5.0,0.0,0.0,NaN,0.048790,NaN,0.0,0.0,0.0,0.0
6048802,PAK,PAK,2023,970110,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048803,PAK,PAK,2023,970190,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048804,PAK,PAK,2023,970300,3.00,3.00,5.0,5.0,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0
6048805,PAK,PAK,2023,970600,3.00,3.00,NaN,NaN,3.0,3.0,0.0,0.0,NaN,0.029559,NaN,0.0,0.0,0.0,0.0

In [72]:
update = pd.read_csv("DATASET_FOR_UPDATE_APRIL28.csv", dtype={"i_iso": str, "j_iso": str, "k": str})
update.rename(columns={'j':'j_iso', 'i':'i_iso'}, inplace=True)
update.to_csv('DATASET_FOR_UPDATE_APRIL28.csv', index=False)

In [ ]:
# Save to Stata format
merged.to_stata("thesis_may_updated.dta", write_index=False, version=118)

In [86]:
import pandas as pd

# Load dataset

merged["i_iso"] = merged["i_iso"].str.upper().str.strip()
merged["j_iso"] = merged["j_iso"].str.upper().str.strip()

# Drop rows where exporter == importer
merged = merged[merged["i_iso"] != merged["j_iso"]]


merged.to_csv("thesis_may.csv", index=False)

# Check
print("Remaining rows:", len(df))

Remaining rows: 4624442

In [87]:
import pandas as pd

df = pd.read_excel("res.xlsx")

df["HS6"] = df["HS6"].astype(str).str.zfill(6)
df["HS2"] = df["HS6"].str[:2].astype(int)

def map_section(hs2):
    if 1 <= hs2 <= 5: return 1
    elif 6 <= hs2 <= 14: return 2
    elif hs2 == 15: return 3
    elif 16 <= hs2 <= 24: return 4
    elif 25 <= hs2 <= 27: return 5
    elif 28 <= hs2 <= 38: return 6
    elif 39 <= hs2 <= 40: return 7
    elif 41 <= hs2 <= 43: return 8
    elif 44 <= hs2 <= 46: return 9
    elif 47 <= hs2 <= 49: return 10
    elif 50 <= hs2 <= 63: return 11
    elif 64 <= hs2 <= 67: return 12
    elif 68 <= hs2 <= 70: return 13
    elif hs2 == 71: return 14
    elif 72 <= hs2 <= 83: return 15
    elif 84 <= hs2 <= 85: return 16
    elif 86 <= hs2 <= 89: return 17
    elif 90 <= hs2 <= 92: return 18
    elif hs2 == 93: return 19
    elif 94 <= hs2 <= 96: return 20
    elif hs2 == 97: return 21

df["section"] = df["HS2"].apply(map_section)

result = df.groupby("section").agg(
    avg_elasticity=("epsilon", "mean"),
    num_regressions=("epsilon", "count")
)

print(result)

         avg_elasticity  num_regressions
section
1            -51.237480              110
2            -38.666441              162
3            -51.511287               28
4            -24.071893              126
5            -48.090971               37
6            -37.324591              393
7            -31.232231              177
8            -27.776500               37
9            -43.848139               44
10           -57.015287               93
11           -32.055160              423
12           -24.298284               17
13           -33.062088               99
14           -28.047571               17
15           -40.993184              322
16           -39.031603              434
17           -34.497159               53
18           -42.696881              152
19           -30.477551                9
20           -23.523788               94

In [93]:
import pandas as pd

df = pd.read_excel("res.xlsx")

df["HS6"] = df["HS6"].astype(str).str.zfill(6)
df["HS2"] = df["HS6"].str[:2].astype(int)

def map_section(hs2):
    if 1 <= hs2 <= 5: return 1
    elif 6 <= hs2 <= 14: return 2
    elif hs2 == 15: return 3
    elif 16 <= hs2 <= 24: return 4
    elif 25 <= hs2 <= 27: return 5
    elif 28 <= hs2 <= 38: return 6
    elif 39 <= hs2 <= 40: return 7
    elif 41 <= hs2 <= 43: return 8
    elif 44 <= hs2 <= 46: return 9
    elif 47 <= hs2 <= 49: return 10
    elif 50 <= hs2 <= 63: return 11
    elif 64 <= hs2 <= 67: return 12
    elif 68 <= hs2 <= 70: return 13
    elif hs2 == 71: return 14
    elif 72 <= hs2 <= 83: return 15
    elif 84 <= hs2 <= 85: return 16
    elif 86 <= hs2 <= 89: return 17
    elif 90 <= hs2 <= 92: return 18
    elif hs2 == 93: return 19
    elif 94 <= hs2 <= 96: return 20
    elif hs2 == 97: return 21

df["section"] = df["HS2"].apply(map_section)

result = df.groupby("section").agg(
    avg_elasticity=("epsilon", "mean"),
    std_dev=("epsilon", "std"),
    min_elasticity=("epsilon", "min"),
    num_regressions=("epsilon", "count")
).reset_index()

print(result)

    section  avg_elasticity    std_dev  min_elasticity  num_regressions
0         1      -51.237480  26.196756      -97.381248              110
1         2      -38.666441  27.029997      -91.993378              162
2         3      -51.511287  25.940585      -71.096771               28
3         4      -24.071893  14.137436      -83.773636              126
4         5      -48.090971  23.253547      -92.335251               37
5         6      -37.324591  23.319153      -98.503532              393
6         7      -31.232231  17.252789      -89.326370              177
7         8      -27.776500  13.579971      -62.671642               37
8         9      -43.848139  21.136348      -90.481705               44
9        10      -57.015287  29.785666      -97.733032               93
10       11      -32.055160  23.115834      -96.797585              423
11       12      -24.298284   9.310065      -34.040874               17
12       13      -33.062088  17.868240      -89.667755               99
13       14      -28.047571  22.703801      -68.907349               17
14       15      -40.993184  25.120414      -99.119606              322
15       16      -39.031603  21.790977      -99.592415              434
16       17      -34.497159  23.314813      -96.631165               53
17       18      -42.696881  20.292669      -99.408943              152
18       19      -30.477551   1.914559      -33.185146                9
19       20      -23.523788  20.710113      -86.455917               94

In [95]:
import pandas as pd

# Load data
df = pd.read_excel("res.xlsx")

# Ensure HS6 is string and correctly formatted
df["HS6"] = df["HS6"].astype(str).str.zfill(6)

# Extract HS2
df["HS2"] = df["HS6"].str[:2].astype(int)

# Map to HS sections
def map_section(hs2):
    if 1 <= hs2 <= 5: return 1
    elif 6 <= hs2 <= 14: return 2
    elif hs2 == 15: return 3
    elif 16 <= hs2 <= 24: return 4
    elif 25 <= hs2 <= 27: return 5
    elif 28 <= hs2 <= 38: return 6
    elif 39 <= hs2 <= 40: return 7
    elif 41 <= hs2 <= 43: return 8
    elif 44 <= hs2 <= 46: return 9
    elif 47 <= hs2 <= 49: return 10
    elif 50 <= hs2 <= 63: return 11
    elif 64 <= hs2 <= 67: return 12
    elif 68 <= hs2 <= 70: return 13
    elif hs2 == 71: return 14
    elif 72 <= hs2 <= 83: return 15
    elif 84 <= hs2 <= 85: return 16
    elif 86 <= hs2 <= 89: return 17
    elif 90 <= hs2 <= 92: return 18
    elif hs2 == 93: return 19
    elif 94 <= hs2 <= 96: return 20
    elif hs2 == 97: return 21

df["section"] = df["HS2"].apply(map_section)

# Aggregate
result = df.groupby("section").agg(
    avg_elasticity=("epsilon", "mean"),
    std_dev=("epsilon", "std"),
    min_elasticity=("epsilon", "min"),
    num_regressions=("epsilon", "count")
).reset_index()

# Save results to Excel
result.to_excel("HS_section_results.xlsx", index=False)

print("Saved to HS_section_results.xlsx")

Saved to HS_section_results.xlsx